### ISSUE TITLE
Calculation method for average hospital admissions on regional level unclear

### ISSUE THREAD

**Issue by boisei0** [minvws/nl-covid19-data-dashboard#111]
On the regional level page of the dashboard, local data per "veiligheidsregio" is displayed. This includes average hospital admittances over the last 3 days. This is shown (in Dutch) as "Aantal mensen met COVID-19 dat per dag in een ziekenhuis is opgenomen. Dit cijfer is een gemiddelde van de gemelde ziekenhuisopnames over de afgelopen 3 dagen."
It is sourced as the daily statistics from the RIVM. On a national level, it can be derived how many patients got admitted to the hospital every day. For regional, it appears as if only cumulative data is published, and because of corrections it's unclear in which area those took place. As such, given the RIVM data file for cumulative cases per municipality, it is possible to calculate the difference between the days and as such get a daily value per region by adding all municipalities within a "veiligheidsregio" together. Using those daily changes, an average can be calculated. 
Based on the data, it can't be derived how many patients got released from the hospital and how many admitted on a given day. However, calculations can be done in which it is assumed that the difference between the days are the admittances. Since it is possible for that difference to come back negative (which would translate to more people released than admitted), including those in the averages might match the description of "admittances" specifically. 

I took the raw data file for cumulative cases per municipality (https://data.rivm.nl/covid-19/COVID-19_aantallen_gemeente_cumulatief.json), and used those to calculate the 3 day average on hospital admittances per "veiligheidsregio", which I compared to the data the dashboard returns for those same "veiligheidsregio's".
The initial method I used mostly matched the Corona Dashboard data: calculate the difference between the days, and use that to get a 3 day average. The alternative method had a lot more discrepancies compared by the data shown on the Dashboard: for days where the daily difference is lower than 0, set it to 0. This resulted in a lot more different averages. 
The script for these calculations can be seen here for reference: https://github.com/boisei0/bddataplan-corona-locator-scripts/blob/3b55443dc8de778ffe71cf496817afbc9879ba04/compare_rivm_data_to_dashboard.py

Going back to the initial method, in situations where the average would have been negative with this method, it appears as `0.0` on the dashboard in the data. This appears to be the situation for 89 values, spread over 19 different "veiligheidsregio's". 

Would you be able to comment on the calculation method used to show these values on the (regional) dashboard, and is the code generating the datasource that powers the dashboard publicised anywhere? 

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by boisei0** [comment]
Additionally to the last point, but potentially better suited in its own issue, other values are getting historical updates as well, such as infections at nursery homes. Compared to yesterday, 22 locations were shown, whereas today 24 locations can be found. Looking at the data, and in the diagram displayed, it shows that the +2 locations were retroactively added for August 6th. As such, for viewers comparing yesterday with today, it would technically be correct that no new locations were reported in the last 24 hours, however as they were retroactively reported in the last 24 hours and historically added, it won't add to the transparency that this dashboard is supposed to provide.

**Comment by VWSCoronaDashboard** [comment]
Thanks for reporting this. We're planning to open source the calculation project shortly which should answer most of your questions on how things get calculated. We'll comment on this issue once that happens. Your feedback on the calculation methods and effects has been forwarded to the data team involved, who are actively working on issues like you describe. We agree that there are downsides to the current method used for calculation. We're working with the RIVM on an alternative approach.

**Comment by VWSCoronaDashboard7** [comment]
See https://github.com/minvws/nl-covid19-data-backend-processing for the now available background information on calculations. As that project is specifically about calculations, any questions or discussions are best suited there. Closing this issue for that reason.
