### ISSUE TITLE
Feature request: Distribution by age for Safety regions and Municipalities

### ISSUE THREAD

**Issue by EwoutH** [minvws/nl-covid19-data-dashboard#1148]
Would it be possible to add the _Distribution by age_ graph to the pages of each safety region and municipality? I find it very useful!

**Comment by VWSCoronaDashboard7** [comment]
We'll look into that! We're getting mixed feedback about the graph's complexity so we're looking at it again anyway. Will take this request into account when considering next steps.

**Comment by VWSCoronaDashboard7** [comment]
Asked around, no data available for it. Closing.

**Comment by EwoutH** [comment]
Unfortunate to hear, but thanks for looking into it
