### ISSUE TITLE
Report case count B.1.1.7 (UK) and B.1.351 (South Africa) variants

### ISSUE THREAD

**Issue by EwoutH** [minvws/nl-covid19-data-dashboard#1310]
Currently there are two major new SARS-CoV-2 variants spreading world wide:

- [B.1.1.7](https://cov-lineages.org/global_report_B.1.1.7.html) (likely origin the United Kingdom)
- [B.1.351](https://cov-lineages.org/global_report_B.1.351.html) (likely origin South Africa)

It would be very useful to have the case count in The Netherlands of these and other major variants integrated on the dashboard, ideally daily and per region. 

On December 28th [the RIVM reported](https://www.rivm.nl/en/news/spread-of-uk-coronavirus-variant-in-netherlands):

> The UK variant of the coronavirus (SARS-CoV-2) has been found in 11 people in the Netherlands so far: 5 people in the Amsterdam region, 5 people in the Rotterdam region and 1 person in the Nijmegen region.

Like both [Henk-Jan Westeneng](https://twitter.com/HJWesteneng/status/1345395273267367937) and [Marino van Zelst](https://twitter.com/mzelst/status/1345774473958588418) pointed out, these variants are a paradigm shift. We almost have to thread them as a whole new virus, that spreads between 40% and 70% faster. In February it will most likely contain the majority of the cases and in March practically all new cases.

The public needs to be made aware of this support and understanding, and policy makers need to be able to track the developments of the SARS-CoV-2 variants precisely.

If the RIVM doesn't publish this information publicly yet, they need to be urged to start doing this as fast as possible.

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by EwoutH** [comment]
The two reports above were updated a few hours ago, with a lot more cases found of the B.1.1.7 variant (see [this diff](https://web.archive.org/web/diff/20210103215915/20210104135130/https://cov-lineages.org/global_report_B.1.1.7.html)). The UK updated from UK 4566 to 5040, Denmark from 33 to 76 and Portugal from 20 to 35. Also the first four cases were found in Jamaica, a third case in Germany, a second in France and the first two in Pakistan.

The Netherlands lags a bit behind in this report, because the RIVM hasn't published all sequences to GISAID yet. See https://github.com/cov-lineages/lineages-website/issues/3.

Publishing daily and localized B.1.1.7 on https://data.rivm.nl/covid-19/ and integrating them into the dashboard is essential for creating public awareness and building trust (by transparency).

For implementation on the Dashboard, I would suggest a new category _Variants_ with items _B.1.1.7 cases found_ and _B.1.135 cases found_. The country of origin could be added in the description for example. Each of those items could look like _Number of confirmed cases_, with 1) the average per 100.000 inhabitants, 2) the number of confirmed cases 3) a map with the distribution, 4) the progression over time and 5) the distribution by age.

**Comment by EwoutH** [comment]
The RIVM announced Wednesday that VOC 202012/01 (know as lineage B.1.1.7) now has been detected by about 50 people:

- [Update verspreiding Britse coronavariant (VOC 202012/01) in Nederland](https://www.rivm.nl/nieuws/update-verspreiding-britse-coronavariant-voc-20201201-in-nederland)

@VWSCoronaDashboard Could you look into integrating these numbers into the Dashboard at soon as possible?

**Comment by EwoutH** [comment]
Sewage water measurements of B.1.1.7 and B.1.351 lineages could also added, when the data becomes available. 
- [Detection of SARS-CoV-2 variants in Switzerland by genomic analysis of wastewater samples](https://www.medrxiv.org/content/10.1101/2021.01.08.21249379v1)

**Comment by VWSCoronaDashboard7** [comment]
We've added data from the 'kiemsurveillance' which gives insight into this. It's not something measured for each confirmed case so this is the best we have: https://coronadashboard.rijksoverheid.nl/landelijk/varianten
