### ISSUE TITLE
Eemsdelta en Haaren

### ISSUE THREAD

**Issue by rikstrijker** [minvws/nl-covid19-data-dashboard#1332]
### Municipalities merged

In the province of Groningen three municipalities merged: Appingedam, Delfzijl and Loppersum. Since the first of January 2021 the new municipality is called Eemsdelta.

However a search for Eemsdelta gives no result. The same for the map, Appingedam, Delfzijl and Loppersum are still separate municipalities. 

![Selection_024](https://user-images.githubusercontent.com/57141365/103634874-f95fa780-4f47-11eb-8c95-6e547a231b22.png)

For Haaren in Noord-Brabant the opposite happens, the municipality is now part of  Boxtel, Oisterwijk, Vught and Tilburg. 
![Selection_025](https://user-images.githubusercontent.com/57141365/103635338-aafed880-4f48-11eb-81da-326d049266d1.png)

### Expected behavior
Eemsdelta should give a result, Appingedam, Delfzijl and Loppersum should not be listed. 
Haaren should not be listed 

**Desktop:**
 - OS: Ubuntu 20.04.1 LTS
 - Browser firefox
 - Version 84.0 (64-bit)
 - Browser Google Chrome
 - Version 87.0.4280.88 (Official Build) (64-bit)
 - Browser Chromium
 - Version 87.0.4280.88 (Official Build) snap (64-bit)

### Additional context
[Eemsdelta](https://www.rijksoverheid.nl/onderwerpen/gemeenten/documenten/publicaties/2020/03/02/herindelingsadvies-gemeente-appingedam-delfzijl-en-loppersum
)
[Haaren](https://www.rijksoverheid.nl/onderwerpen/gemeenten/documenten/rapporten/2019/06/06/herindelingsadvies-gemeenten-haaren-oisterwijk-vught-boxtel-en-tilburg
)
### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard** [comment]
Hey @rikstrijker!

Take a look at https://github.com/minvws/nl-covid19-data-dashboard/pull/1271.
We're aware of the change, but not everything is in place yet to merge the feature.

I'll keep this issue open for now, but rest assured it's already being actioned. 👍

**Comment by VWSCoronaDashboard** [comment]
@rikstrijker 

Here's [the municipal page for Eemsdelta](https://coronadashboard.rijksoverheid.nl/gemeente/GM1979/positief-geteste-mensen).
