### ISSUE TITLE
Feature request: Percentage positief per leeftijdsgroep

### ISSUE THREAD

**Issue by EwoutH** [minvws/nl-covid19-data-dashboard#1340]
In het [wekelijkse epidemiologische rapport](https://www.rivm.nl/en/node/163991) wordt op pagina 34 het percentage positief geteste personen per leeftijdsgroep gemeld. Is het mogelijk dat dit wekelijkse percentage op het Dashboard wordt vermeld? Dit zou bijvoorbeeld een lijngrafiek kunnen zijn, met voor elke leeftijdsgroep een eigen kleur lijn, en op de x-as de week en op de y-as het percentage.

Met het sterk wisselende aantal testen is een percentage positief een stuk betere indicator dan het aantal positieve testen zelf.

<img width="806" alt="Screenshot_317" src="https://user-images.githubusercontent.com/15776622/103660475-ebbd1880-4f6d-11eb-8661-d76d41ebaf0c.png">

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by PieterKnops** [comment]
Deze cijfers zouden goed bij de "Verdeling naar leeftijd" passen bij het dashboard:
![image](https://user-images.githubusercontent.com/15109018/103911045-da0e7900-5105-11eb-899f-92fbd6e9f7e4.png)

Nu lijkt het net alsof de leeftijdsgroep 0-9 relatief gezien het minst besmet raakt, terwijl de cijfers uit de afbeelding bij @EwoutH erop zouden wijzen dat ze juist het meest besmettelijk zouden zijn. Vandaar dat het mij goed lijkt de cijfers eenvoudig naast elkaar te kunnen zien.

**Comment by VWSCoronaDashboard7** [comment]
It's an interesting thought. The difficulty here is that it would require 11 lines to be plotted in a graph. All age groups plus the number of tests per day as a reference point for the percentage. That's simply too many lines for the graph to sufficiently interpretable for the majority of users.

This is why we, for the time being, opted for the age division graph posted above. While it doesn't show the progression over time well, it does give a good idea on the spread by age-group in recent confirmed cases.

**Comment by DavyLandman** [comment]
I've been making such a graph based on RIVM reports, it's quite readable.

![image](https://user-images.githubusercontent.com/179603/106010671-004a8780-60ba-11eb-8fb6-d2b4bc0aa492.png)

**Comment by PieterKnops** [comment]
@VWSCoronaDashboard7, also, it is not needed per sé to have a time axis. Just a graph as in my last comment would be sufficient to get a general idea of the relative spread in each age category.

**Comment by VWSCoronaDashboard7** [comment]
We've added the confirmed cases per age-group on a per 100.000 scale. See https://coronadashboard.rijksoverheid.nl/landelijk/positief-geteste-mensen - whilst not exactly the same as the percentage of positive tests it should give a good impression of the relative amount of confirmed cases in each agegroup.

<img width="784" alt="Screenshot 2021-05-06 at 12 09 19" src="https://user-images.githubusercontent.com/70589785/117281536-0ba11200-ae64-11eb-88be-3770e4373f7f.png">
