### ISSUE TITLE
Feature request: number of vaccinated people

### ISSUE THREAD

**Issue by reharmsen** [minvws/nl-covid19-data-dashboard#1377]
It would be really informative to know how many persons are vaccinated...
Also to see whether positive tests declines when vaccination rate increasses.

**Comment by edomt** [comment]
I second that! 👍

**Comment by VWSCoronaDashboard** [comment]
Related: https://github.com/minvws/nl-covid19-data-dashboard/pull/1335

**Comment by VWSCoronaDashboard** [comment]
https://github.com/minvws/nl-covid19-data-dashboard/pull/1433

**Comment by VWSCoronaDashboard7** [comment]
As you see in previous comments we're already preparing for this. From our FAQ:

_We willen graag zo snel mogelijk data over vaccinaties op het dashboard laten zien, onder andere over het aantal toegediende vaccins. Daarvoor hebben we exacte en volledige data nodig van alle betrokken partijen. Samen met de partijen die vaccineren en andere betrokken partijen werken we daar hard aan. Zodra de datastroom geregeld is, komen de gegevens op het dashboard._

Revised and updated texts always available at https://coronadashboard.rijksoverheid.nl/veelgestelde-vragen#komen-er-ook-cijfers-over-vaccinaties-op-het-dashboard-

**Comment by boisei0** [comment]
In relation to #1335 and the comments there regarding placement of data in the locale files, and the older issue #90 regarding the use of the locale files for placing constants and/or data, is there an ETA for when the vaccination data will be properly added in a schema format, like has been created now for vaccine availability? 

The issue mentioned in #90 regarding values being potentially overwritten in different languages will still hold true, especially as on updates of the value both the Dutch and English locales have to be updated. As #1600 shows, typing errors can be easily made. As the date of report wasn't edited in that commit, I've to assume that it was a typo in the original addition. If such a typo is made in only one locale file, it means there's a difference between both languages of the dashboard. Which is the point that #90 and subsequent issues were making.

**Comment by VWSCoronaDashboard7** [comment]
@boisei0 The switch to proper JSON schema's will happen in the next few weeks. This intermediate solution has obvious drawbacks as you point out but was the most practical solution for a few reasons, one of which is that the data is collected manually at this point in time. See https://coronadashboard.rijksoverheid.nl/verantwoording#vaccinatie for some more details on that. But rest assured: we're also eager to get a proper dataflow going with proper open data.

**Comment by VWSCoronaDashboard7** [comment]
As an update to the comment about JSON schema's, the delivery graph is now fed data properly from https://coronadashboard.rijksoverheid.nl/json/NL.json - the key is "vaccine_delivery" for those interested.

**Comment by icepick3000** [comment]
Could you make the number of vaccines issued and the delivery of vaccines available at https://data.rivm.nl/covid-19/ ?

**Comment by VWSCoronaDashboard** [comment]
@icepick3000 That's something for the RIVM to do and outside of the scope of this repository to discuss. We're big proponents of open data so we are very much in favour of having that data automated via the data-portal as soon as that's feasible. Meanwhile you could get some of the data you're looking for via https://coronadashboard.rijksoverheid.nl/json/NL.json

@boisei0 https://coronadashboard.rijksoverheid.nl/json/NL.json now also contains all data in the KPI's and the delivery graph. Keys are labeled with "vaccine".

**Comment by VWSCoronaDashboard7** [comment]
I'm closing this ticket, the feature is on our backlog and will be added once data is available for it. Meanwhile we work on improving the page where we can.
