### ISSUE TITLE
Bug in "klachten bij huisartsen".

### ISSUE THREAD

**Issue by ToonHermans** [minvws/nl-covid19-data-dashboard#1420]
### Describe the bug, issue or concern
There's a bug in the "klachten bij huisartsen" section. The graph is always on "Toon alles". Putting it on "Laatste 5 waken" does nothing and keeps showing all. The problem is in both the English and Dutch version.

### To Reproduce
1. Go to '["Verloop over tijd" in "Klachten bij huisartsen"](https://coronadashboard.government.nl/landelijk/verdenkingen-huisartsen)'
2. Click on 'Toon alles'
3. Click on 'Laatste 5 weken'
4. Compare the two.

### Expected behavior
'Laatste 5 weken' should only show the last 5 weeks and not everything.

### Screenshots
![image](https://user-images.githubusercontent.com/35902688/104346233-7b7b3d80-54ff-11eb-90a9-8f8a6e729fd5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (64-bit)
 - Browser: Chrome
 - Version: 87 

### Additional context
No additional context.

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [X] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [X] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard** [comment]
Thank you for the bug report, we will fix this.
