### ISSUE TITLE
Values in "sewage water examinations" map are broken.

### ISSUE THREAD

**Issue by ToonHermans** [minvws/nl-covid19-data-dashboard#1421]
### Describe the bug, issue or concern

The values in the "sewage water examinations" map, which shows the average amount of virus particles per 100.000 inhabitants per safety region are broken. They all show {{value}} instead of an actual value. This only happens on the English version of the dashboard. The Dutch version works fine.

E.g. 

### To Reproduce
1. Go to '"[Sewage water examination" in the English dashboard](https://coronadashboard.government.nl/landelijk/rioolwater)'
2. Scroll down to '"Average number of virus particles per 100.000 inhabitants" map'
3. Hover mouse of the map to see {{value}}

### Expected behavior
Expected to see an actual value on the map "Average number of virus particles per 100.000 inhabitants", but instead saw {{value}}.

### Screenshots
![image](https://user-images.githubusercontent.com/35902688/104347541-07419980-5501-11eb-846f-452853159e57.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (64-bit)
 - Browser: Chrome
 - Version: 87

### Additional context
No additional context.

### Governance
- [X] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [X] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [X] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard7** [comment]
Hi! Thanks for the report. It was a missing value in our locale files and has been corrected. Production now shows the values again.
