### ISSUE TITLE
Reported hospitalisations is not reflected correctly in the corresponding graph

### ISSUE THREAD

**Issue by great7ven** [minvws/nl-covid19-data-dashboard#1534]
### Describe the bug, issue or concern

Reported hospitalisations is not reflected correctly in the corresponding graph

### To Reproduce
    1. Go to 'https://coronadashboard.rijksoverheid.nl/landelijk/ziekenhuis-opnames'
    2. See error, in the left screen you see "ziekenhuisopnames" with a number (19-01-2021, 256), in the graph the day of yesterday is shown with the number 79, that's not even the number of "ziekenhuisopnames" of yesterday but it looks like the number of nursinghome care "verpleeghuiszorg". It's clearly not a correct number on the last shown day, the graph also feels not correct on the last day.

### Expected behavior
Show the correct number for the day in the graph..

### Screenshots
<img width="1920" alt="Screenshot_2021-01-19 Ziekenhuisopnames Dashboard Coronavirus Rijksoverheid nl" src="https://user-images.githubusercontent.com/20112266/105181584-476dd100-5b2c-11eb-9d00-d45de280338b.png">

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox
 - Version 84.0.2

**Smartphone (please complete the following information):**

### Governance
- [v] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [v] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [v] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard7** [comment]
Hi, thanks for the report. The data is correct, as the description of the linegraph states:

_The figure for each day indicates the number of people actually admitted on that day, not the number of admissions reported on that day. This gives a clear picture of the development of coronavirus in the Netherlands._

So there's a different definition for that graph than for the KPI's. We are getting more user reports this is confusing and are looking into a better way to combine both daily reports and daily admissions in the linegraph for the next iteration. To be continued!

**Comment by great7ven** [comment]
Hi @VWSCoronaDashboard7,

So you show a graph with numbers of a specific parameter, and then the last day you show something completely different. That's not confusing, that's incorrect. The only way to justify that is working at the governement.
