### ISSUE TITLE
Verkeerde waarde Positieve tests A'dam-Amstelland

### ISSUE THREAD

**Issue by Jan-E** [minvws/nl-covid19-data-dashboard#1615]
In het overzicht van Positief geteste personen in Amsterdam-Amstelland pakken jullie de waarde per 1 juni:

![1juni](https://user-images.githubusercontent.com/1757825/105860329-bbf1b580-5fed-11eb-84d0-309c686f5ed2.png)

Screenshot van huidige output op https://coronadashboard.rijksoverheid.nl/veiligheidsregio/VR13/positief-geteste-mensen

**Comment by VWSCoronaDashboard7** [comment]
Thanks for reporting this! We've identified the cause and will look into getting this fixed.

**Comment by VWSCoronaDashboard7** [comment]
We've released an update that fixes this issue. Thanks again for bringing this up.
