### ISSUE TITLE
Non-existing ‘actueel’ at gemeente level

### ISSUE THREAD

**Issue by Jan-E** [minvws/nl-covid19-data-dashboard#1699]
If you click on Amsterdam in the map and subsequentely on ‘Amsterdam’ on https://coronadashboard.rijksoverheid.nl/veiligheidsregio/VR13/positief-geteste-mensen it links to https://coronadashboard.rijksoverheid.nl/gemeente/GM0363/actueel

There is no actueel on the gemeente level: 404. Er is iets misgegaan.

**Comment by VWSCoronaDashboard7** [comment]
Hi! Thanks for bringing this to our attention. We've just published a minor update which fixes this.
