### ISSUE TITLE
Cosmetic: news article zooms differently when selected

### ISSUE THREAD

**Issue by confusingSmile** [minvws/nl-covid19-data-dashboard#1701]
About div with class "editorial-teaser__StyledTextOverlay-qje20s-0 jBURYC", 
Normally when you mouse over, the image zooms. 

When rightclicking it and then pressing escape, or in a more logical situation when clicking the image with the middle mouse button, the image stays zoomed in, but on mouse over the text becomes larger.

E.g. 

### To Reproduce
1. Open Firefox version 85.0 
2. go to https://coronadashboard.rijksoverheid.nl/
3. click the image in the div with class "editorial-teaser__StyledTextOverlay-qje20s-0 jBURYC"
4. Apart from a new tab opening (part of the intended behaviour), the image stays zoomed in and now the text responds to mouseover by becoming larger

### Expected behavior
The image will zoom out, or it will stay zoomed in; the text will not increase nor decrease in size. 

### Screenshots
https://imgur.com/a/yrfhOng

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - Browser Firefox
 - Version 85.0

### Additional context
None

### Governance
- [V] I've not read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [V] I've not read, but probably understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [V] I probably understand that any contributions or suggestions I made may make it into the actual code. I've not read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt nor the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard14** [comment]
This should be fixed now, thanks for noticing.
