### ISSUE TITLE
Feature Request: Show graph on vaccination statistics

### ISSUE THREAD

**Issue by basdejong95** [minvws/nl-covid19-data-dashboard#1749]
Hi,

It would be nice to see a graph on the vaccination statistics section instead of only a number. 

Please include in the graph:

Number of vaccines in stock
Number of first vaccinated people
Number of fully vaccinated people

Would also be nice to provide some kind of forecast lines

**Comment by VWSCoronaDashboard** [comment]
Hi! We're working on several vaccination-related infopoints which we'll roll out over the coming weeks pending data availability. Whether "in stock" will be present in those is still a question mark. You need a lot of context on how the delivered, delivery and (planned) use are intertwined to be able to "read" such a graph correctly. But we're thinking about it, so stay tuned :-)
