### ISSUE TITLE
Warning "landelijke lockdown tot 2 maart" can be interpreted in two ways

### ISSUE THREAD

**Issue by NielsLeenheer** [minvws/nl-covid19-data-dashboard#1850]
### Describe the bug, issue or concern

On top of the dashboard is currently a warning with the text: 
`Er geldt een landelijke lockdown tot 2 maart.`

This can be interpreted into two ways:
- Until 2 march, excluding 2 march
- Until 2 march, including 2 march

It is better to use a more clear language to indicate what interpretation is correct.

### To Reproduce
1. Open the dashboard
2. See the warning in the header

### Expected behavior
Use more clear language, for example:
`Er geldt een landelijke lockdown tot en met 2 maart.`

This is consistent with:
https://www.rijksoverheid.nl/onderwerpen/coronavirus-covid-19/vraag-en-antwoord/persconferentie-coronavirus-2-februari-in-eenvoudige-taal:
`Maatregelen tot en met minimaal 2 maart`

https://www.rijksoverheid.nl/onderwerpen/coronavirus-covid-19/algemene-coronaregels/kort-overzicht-coronamaatregelen
`Lees hier wat geldt op dit moment tot en met ten minste 2 maart 2021`

### Screenshots
<img width="822" alt="Screenshot 2021-02-08 at 12 22 51" src="https://user-images.githubusercontent.com/233230/107213206-5e576300-6a08-11eb-8827-424d5e1fd3e5.png">

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard7** [comment]
Hi, this makes sense. I'll forward the feedback to the team responsible for texts on the site. Thanks for taking the time to signal this!
