### ISSUE TITLE
Search input unchangeable after selecting a result using command+enter combination.

### ISSUE THREAD

**Issue by Ezrabeer** [minvws/nl-covid19-data-dashboard#1868]
### Describe the bug, issue or concern

When using the command+enter keys on a search result for the muncipality/safety region, another page opens. If you then go back to the initial page the search input is disabled and can only be re-enabled by refreshing the page. 

### To Reproduce
1. Go to https://coronadashboard.rijksoverheid.nl/.
2. Click on the search input for searching for the muncipality/safety region.
3. Type 'a'.
4. Highlight a result with either the mouse or the keyboard.
5. Use the meta+space key combination to open the result on another page.
6. Head back to the initial page.
7. Try to change the input.

### Expected behavior
The search input should be changeable after you're finished looking at a specific muncipality/safety region on a different page.

**Desktop:**
 - OS: macOS Big Sur
 - Browser: Safari/Google Chrome
 - Version: 
    - Safari: 14.0.1 (16610.2.11.51.8)
    - Google Chrome: 88.0.4324.150

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard** [comment]
That's an interesting bug, thanks for the report. I'm able to reproduce and we'll work on this!
