### ISSUE TITLE
Highest value on y axis on 2 graphs are not fully displayed

### ISSUE THREAD

**Issue by PietPizza** [minvws/nl-covid19-data-dashboard#1954]
This is a really small display issue but it would be nice if it was fixed. 
I searched the entire website for more similar errors, but only found these two. 

In the "Aantal testen over tijd" graph, 100.000 is not fully displayed.
https://coronadashboard.rijksoverheid.nl/landelijk/positief-geteste-mensen

![image](https://user-images.githubusercontent.com/19930067/108195043-9a30ad80-7117-11eb-9ba4-c574cacbcdb1.png)

In the "Totaal aantal besmette locaties over tijd" graph, 1000 is not fully displayed.
https://coronadashboard.rijksoverheid.nl/landelijk/verpleeghuiszorg

![image](https://user-images.githubusercontent.com/19930067/108195781-8c2f5c80-7118-11eb-98bf-481b0180a86d.png)

**Comment by VWSCoronaDashboard** [comment]
Thanks for pointing this out - we've put it on our "to fix" list.

**Comment by VWSCoronaDashboard7** [comment]
This should be resolved now! Forgot to update this issue. Will close it now.
