### ISSUE TITLE
Date axis for nursery homes is incorrectly displayed

### ISSUE THREAD

**Issue by mzelst** [minvws/nl-covid19-data-dashboard#199]
Hi,

I was just checking the dashboard and the dates for nursery homes are incorrectly displayed, depending on the choice for the time period. For 'Toon alles' and 'Laatste 5 weken', it currently only displays until August 9th. For 'Laatste week', the data is correctly displayed.

Could you look into this? Please find a screenshot attached of what I see. I've tried this from both my laptop and phone and it shows the same results.

![image](https://user-images.githubusercontent.com/12472917/91585391-4b6a3e00-e954-11ea-960d-c25d456e7c47.png)

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard** [comment]
This looks fixed on production. Can we close this @mzelst?

**Comment by mzelst** [comment]
This issue can be closed. Thank you for fixing this and your response!
