### ISSUE TITLE
Mention timeframe or date of measurement in first paragraph for all tiles

### ISSUE THREAD

**Issue by jurb** [minvws/nl-covid19-data-dashboard#2]
A lot of tiles have a description of the timeframe / date of the measurement (e.g. 'Aantal opnames per dag, gemiddeld over de afgelopen 3 dagen.'). 

Some don't however (e.g. 'Aantal positief geteste mensen per 100.000 inwoners per dag.'). 

I think it would be clear to mention the timeframe / measurement date in all tiles (in the paragraph beneath the title). We can adjust the last example to 'Aantal positief geteste mensen per 100.000 inwoners per dag, gemeten op 5 juni', for example.

**Comment by VWSCoronaDashboard7** [comment]
This has been applied more consistently.
