### ISSUE TITLE
Positive test, distriburion of agegroup not showing relative to tests done for agegroup

### ISSUE THREAD

**Issue by cjvanzwol** [minvws/nl-covid19-data-dashboard#2048]
# Situation
Get dashboard shows a barchart with age groups. On the left is the distribution of the groups in the dutch population. On the right is the distribution of the positive tests. 

It tells us how many people of the population were tested positive.

https://coronadashboard.rijksoverheid.nl/landelijk/positief-geteste-mensen

# Problem
What I miss is the distribution of the total taken tests distribution of agegroups.

# Proposed solution
Adding stacked bar onto the right bar which indicates percentage of total taken tests. 

Other grafics which shows the percentage of taken tests within the agegroup population would also fix this issue.

**Comment by VWSCoronaDashboard7** [comment]
Yes, that would be valuable information. Since we're replacing that graph within the next couple of weeks it becomes a moot point though and therefore I'm closing this issue.
