### ISSUE TITLE
Taken and positive tests distribution in agegroups over time

### ISSUE THREAD

**Issue by cjvanzwol** [minvws/nl-covid19-data-dashboard#2051]
# Situation
Since the 9th of February the primary schools in the Netherlands atre reopened.

One condition of this opening is that if one child in a class has tested positive, the whole class should go into quarantine and be tested after 5 days. 

# Hypothesis
The condition would imply the number of tests within the agegroup of 4-12 would rise more than within other age groups. 

Secondly would it be very useful to inspect whether children are getting more (or no more) contagion now they have more contact than when schools were closed. 
So changes distribution of positive tests within age groups over time would be a useful addition.

# Solution
Adding a linechart with a line for taken tests and positive tests over time.
For readability (especially on mobile devices) age groups could be selectable and interactively changing the visualization.

**Comment by VWSCoronaDashboard7** [comment]
We're currently working on adding the number of confirmed cases  (see https://github.com/minvws/nl-covid19-data-dashboard/pull/2359 for example for the schema on it) by age-group which would give you this insight. Expect this to appear within a the next few weeks.

**Comment by cjvanzwol** [comment]
The dashboard now shows a chart with positive tests per agegroup. It still lacks a chart with total number of taken tests per agegroup.  The chart at the bottom is a chart like that, but that is for the entire population. 

I hoped you would add the numbers of taken tests per agegroup, but you didn't. 

Are you planning on adding those data and charts?
