### ISSUE TITLE
 graph for sewage measurement for Oldenzaal is flashing

### ISSUE THREAD

**Issue by jeroenbreen** [minvws/nl-covid19-data-dashboard#211]
### Describe the bug, issue or concern

The graph for sewage measurement for the municipality Oldenzaal is flashing

### To Reproduce
Go to https://coronadashboard.rijksoverheid.nl/regio?regio=GM0173 and check section 'Rioolwatermeting in Oldenzaal'

### Suggestions
Could it be related to the fact that 2 sewage measurement plants (Tweede Exloermond (3023) and Oldenzaal (5012)) are situated in Oldenzaal?
See also: https://innouveau.com/projecten/corona/kaart/#/?city=Oldenzaal

**Comment by VWSCoronaDashboard7** [comment]
Thanks for the spot. This has been resolved.
