### ISSUE TITLE
Feature request: 7-day floating average

### ISSUE THREAD

**Issue by MikeBrachten** [minvws/nl-covid19-data-dashboard#2115]
### Context
As covid-related data varies from day to day, it seems useful to judge the (historical) epidemiological situation by the increase or decrease of positive tests compared to the 7-day average. Various news outlets in the Netherlands (like nu.nl, de Telegraaf, nos) started to report the day counts compared to this measure, and I think it would be useful to implement this in coronadashboard for easier access to its users.

### Idea
I propose to implement a new graph (or line which can be enabled for easier comparison) that displays the 7-day floating average. I could look something like the mock-ups down below.
#### Disclaimer
Please note that the values in the following mock-up are not real.
### Mock-ups
![Web 1920 – 1](https://user-images.githubusercontent.com/18405056/109436479-fcdf4e80-7a1f-11eb-9275-7fd8a04766b4.png)
_Figure 1: Special graph for floating average_

![Web 1920 – 2](https://user-images.githubusercontent.com/18405056/109436482-010b6c00-7a20-11eb-88fe-772c962f0256.png)
_Figure 2: Floating average trendline in current graph_

**Comment by VWSCoronaDashboard7** [comment]
It will definitely make sense to add this. The feature has been on our backlog for a while now and with news media showing it as well we think that it's meaning is more easily grokked by the general audience. We're going to put this higher on our list so stay tuned :-)
