### ISSUE TITLE
Feature Request: Vaccine chart breakdown.

### ISSUE THREAD

**Issue by timostrating** [minvws/nl-covid19-data-dashboard#2228]
The Coronadashboard already has a breakdown of the different delivered vaccins and how they combine to the total. It would be nice if an graph like this could be added that shows how many people had 1 vaccin or had 2 vaccins, Some vaccins are more effective after a while so an delayed line that is 2 to 3 weeks slower would also be nice.

Because the data that is required to properly create such a chart is not available on the open data other dashboards can not recreate this graph very accurately.

"Het aantal gemelde prikken wordt dagelijks handmatig bijgewerkt op basis van data van de GGD’en en het LNAZ. Deze data zijn op dit moment nog niet beschikbaar als open data."

https://covid-analytics.nl/vaccination.html comes the most close but its graph contains errors regularly, The small drops are and example of that, That dashboard is based on combining data from Our world in Data, Nieuws articles from Landelijk Netwerk Acute Zorg such as this one https://www.lnaz.nl/nieuws/ziekenhuizen-hebben-13500-medewerkers-acute-zorg-voor-de-2de-keer-gevaccineerd and the opendata from this dashboard.
![image](https://user-images.githubusercontent.com/12185305/110332087-31569a00-8020-11eb-89a2-4536f3147d47.png)

source code https://github.com/Sikerdebaard/opencoronastats/blob/master/scripts/vaccine.py#L19

This request is related to #1377 and #1335 

solutions: Add the data required to make such a graph to the opendata. or add the graph to the dashboard.

P.S. Beetje raar dat Nederlands hier niet de voertaal is, maar ja, vooruit.

**Comment by VWSCoronaDashboard7** [comment]
Hi! Whilst we would love to show numbers about 2nd dose etc, reality is the data is simply not yet available for us to use. We feel it's important to use the source data from RIVM for this. Once that's available there are plans to add more data on vaccinations to the dashboard.

**Comment by timostrating** [comment]
@VWSCoronaDashboard7 I understand that the dashboard want's to only show data from its own sources. But the RIVM is already publishing this data https://www.rivm.nl/covid-19-vaccinatie/cijfers-vaccinatieprogramma so your argument does not hold. There are remarks placed under the tables that say some numbers are estimates but other data on the dashboard also contain estimates so that could not be a problem.

**Comment by VWSCoronaDashboard7** [comment]
@timostrating I'm aware of that RIVM-page, but that is a manually composed data stream which is not preferable for a couple of reasons. There's a data stream in the works, which to my knowledge will also become open data on the RIVM data portal, which we would like to use. So this is coming but we're awaiting that data drop.

**Comment by timostrating** [comment]
Has there been an update on this?
