### ISSUE TITLE
Difficulty getting local environment set up due to Sanity integration

### ISSUE THREAD

**Issue by mpboom** [minvws/nl-covid19-data-dashboard#2236]
### Describe the bug, issue or concern

While trying to follow the README to set up the application locally, I ran into some issues. The `yarn download` command didn't seem to work properly, for which I opened #2235, but I also had some difficulties with what seem to be the integration with Sanity. If any workaround is available, it would be good to mention it in the README.

### To Reproduce
1. Clone the repository
2. Change directory to `packages/app/`
3. Run `yarn`
4. Run `yarn download` (with fix in #2235 applied)
5. Run `yarn dev`
6. Get greeted with error messages

### Expected behavior
I expect this to work and start the development server without any errors.

### Logs
My `.env.local` is exactly the same as the `.env.local.example`, I only updated the `NEXT_PUBLIC_LOCALE`. I also tried changing `NEXT_PUBLIC_SANITY_PROJECT_ID` to something random, but to no avail. This just raises errors in different places (when it actually tries to fetch data).

Not that I think it'll help that much, but here is the log:
https://gist.github.com/mpboom/6c324a7aaf933715c019094a4f179e94

### Additional context
I believe the issue is here that the local environment doesn't seem to function if you don't enter correct credentials for Sanity. To work on the vaccine page, I applied the following changes so no Sanity-related requests are fired:
https://github.com/mpboom/nl-covid19-data-dashboard/commit/88c2cabf8cb751d43093dc09e3b1f6d03dc0d510
But that, of course, is a very limited and cubersome workaround.

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard7** [comment]
Hi, we're aware of this issue and have discussed a few possible workarounds. Will update this ticket once there's news on that.

**Comment by VWSCoronaDashboard7** [comment]
This shouldn't be an issue anymore.

**Comment by mpboom** [comment]
Thanks, improving this allows for others to contribute, too. Sadly, getting a local server running doesn't work out of the box just yet. I opened #3799 to fix the remaining issues.
