### ISSUE TITLE
Inconsistency in colors of the maps of the country

### ISSUE THREAD

**Issue by rickyheijnen** [minvws/nl-covid19-data-dashboard#2244]
### Describe the bug, issue or concern

When you visit the "Ziekenhuisopnames" page the color light grey is used for the value 0 (zero). This has a great contrast with the multiple blue colors that are used for all values above zero. When you visit the "Positieve testen" page, the value 0 (zero) doesn't have the deviant color light grey but is given a light blue color.

### Expected behavior
For visual purposes, I would expect the value zero to always be displayed as light grey on all the maps of the country.

### Screenshots
![image](https://user-images.githubusercontent.com/1956522/110529640-cb4e3d80-8119-11eb-8574-cedfeac22604.png)

![image](https://user-images.githubusercontent.com/1956522/110529744-e9b43900-8119-11eb-9940-fe5649379d1e.png)

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard7** [comment]
Good point, we should make the distinction between 0 and "low values" in the second graph. Will put this on the list.

**Comment by VWSCoronaDashboard7** [comment]
Happy to report we are now taking this into account! See https://coronadashboard.rijksoverheid.nl/landelijk/ziekenhuis-opnames and https://coronadashboard.rijksoverheid.nl/landelijk/positief-geteste-mensen for example. Thanks for the report - this really helps us to continuously improve things.
