### ISSUE TITLE
Access Denied when trying to see municipality data

### ISSUE THREAD

**Issue by tomudding** [minvws/nl-covid19-data-dashboard#2412]
### Describe the bug, issue or concern

Whenever I try to view the stats of a municipality I get a 403 Access Denied for the "HTTP" variant of the website. After this, all other pages also show the 403 Access Denied.

This block appears to persists across browsers on the same device. Duration is probably 5 to 10 minutes.

### To Reproduce
1. Go to https://coronadashboard.rijksoverheid.nl.
2. Click on '[Gemeente](https://coronadashboard.rijksoverheid.nl/gemeente)' in the menubar.
3. Click on any municipality on the map.
4. See error.
5. Navigate to any other page, same error.

Or:

1. Go to https://coronadashboard.rijksoverheid.nl.
2. Scroll down to the map of municipalities.
3. Click on any municipality on the map.
4. See error.
5. Navigate to any other page, same error.

### Expected behavior
No 403 Access Denied.

### Screenshots
![image](https://user-images.githubusercontent.com/4983571/112512099-5aeb2180-8d93-11eb-89cb-9728c428a687.png)
![image](https://user-images.githubusercontent.com/4983571/112512133-62122f80-8d93-11eb-9902-5d5e10ae2637.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, macOS Mojave
 - Browser: Firefox, Chrome, Safari, Edge
 - Version: Latest public stable build.

**Smartphone (please complete the following information):**
 - Device: Honor 10
 - OS: Android 10.0
 - Browser: Firefox 86.1.1, Chrome 89.0.4389.105

### Additional context
N/A

### Governance
- [X] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [X] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [X] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by tomudding** [comment]
I forgot to add that I am fully aware this is not necessarily related to this repository and its contents, however, this is the only place I know where to find people who understand the website and its inner-workings :)

**Comment by VWSCoronaDashboard** [comment]
Hi! No problem. I will report this to the infra-team. We've had a similar issue for some users last year which had to do with some security settings.

**Comment by VWSCoronaDashboard** [comment]
We've investigated this. It's due to a recent update in the map-component which causes an abundance of preload requests that is triggering our firewall settings because it's not deemed normal usage. We'll work towards a fix for that.

**Comment by VWSCoronaDashboard** [comment]
We've published a patch this morning, should now be resolved!
