### ISSUE TITLE
Feature request: vaccines administered daily.

### ISSUE THREAD

**Issue by matthijs88** [minvws/nl-covid19-data-dashboard#2502]
The current statistic of the vaccination progress only describe the accumulated total number of administered vaccines. This graph does not clearly show progress regarding the (trend of the) speed people are vaccinated daily.

This data should already be available, because it is shown (for the current day only) in the illustration mentioning the average interval between each vaccination.

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard** [comment]
We have that on our wishlist as well but do not receive the data in the format you describe, we receive it as shown. Once the data gets to us in an automated fashion we expect to be able to add a graph which more clearly illustrates the progression in number of people vaccinated. For more information on the data and how it's presented, see https://coronadashboard.rijksoverheid.nl/verantwoording#vaccinatie
