### ISSUE TITLE
Overflow of titles on mobile devices

### ISSUE THREAD

**Issue by jobvink** [minvws/nl-covid19-data-dashboard#2520]
### Overflow of titles on mobile devices

On mobile devices such as iPhone, long titles can overflow the design, this happens because the overflow-wrap and hypens css-property of these titles are not specified and set to there default. The correct values should be `overflow-wrap: break-word` and because the page language is already set to nl `hyphens: auto` can be used to break the titles automatically.

### To Reproduce
1. Go to https://coronadashboard.rijksoverheid.nl/landelijk/vaccinaties
2. Set the with of your viewport to 375px
3. Scroll down to 'Vaccinatiebereidheid'
4. The title 'Vaccinatiebereidheid' should overflow the design.

### Expected behavior
Long titles should hyphenate when represent on smaller devices. 

### Screenshots
![IMG_4108](https://user-images.githubusercontent.com/19264233/113581712-ce105580-9627-11eb-993c-c2cddf5c6860.jpg)

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: IOS 14.4.2
 - Browser safari
 - Version 14

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard** [comment]
Thanks for the report! We're aware of the issue and have it on our list of items to fix. We might opt for just using a slightly smaller font-size but appreciate the suggestion to hyphenate.

**Comment by VWSCoronaDashboard8** [comment]
This has been fixed as part of #2816 but is not deployed to production yet. So let's close it when it becomes public.
