### ISSUE TITLE
Sewage water averages are incorrect

### ISSUE THREAD

**Issue by MMeent** [minvws/nl-covid19-data-dashboard#2525]
### Describe the bug, issue or concern

The average in "Most recent measurement per location in Enschede"  is equal to the highest value of 5 shown samples, which (according to maths) is unlikely to be a correct average.

### To Reproduce
1. Go to https://coronadashboard.government.nl/gemeente/GM0153/rioolwater
3. Scroll down to "Most recent measurement per location in Enschede"

### Expected behavior
The average should be an actual average of the shown values OR values that are not taken into account in the average should not be shown, or marked as not used in averaging.

### Screenshots

![image](https://user-images.githubusercontent.com/2960313/113719529-fd899580-96ed-11eb-86d1-07da2e6846be.png)

**Desktop (please complete the following information):**
 - OS: Debian Stretch 10.9
 - Browser: Firefox
 - Version: 88.0b5

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard** [comment]
Hi! The bar shows the most recently available "average" which is for the 4th of April. If you hover over the bars on desktop you can see the measurement date. Agree it's confusing and you would expect it to be the average of the bars below. We have a new solution on the backlog but are still discussing it because it's more complex to read - UI wise. But it's on our radar.
