### ISSUE TITLE
Prikken per dag

### ISSUE THREAD

**Issue by alper** [minvws/nl-covid19-data-dashboard#2574]
Ik zocht een tijdje gisteren en ik kon het aantal prikken per dag niet vinden.

Hier staan een aantal statistieken die er allemaal een beetje omheen draaien:
https://coronadashboard.rijksoverheid.nl/landelijk/vaccinaties

Ik denk dat ook voor een internationaal vergelijk het goed is om de dag erna het aantal prikken van de voorgaande dag te verzamelen en te publiceren.

**Comment by VWSCoronaDashboard** [comment]
Duplicate of https://github.com/minvws/nl-covid19-data-dashboard/issues/2502 - see comment there.
