### ISSUE TITLE
Incorrect date in final data point of the graph 'bezetting gewone ziekehuisbedden'

### ISSUE THREAD

**Issue by wickyw** [minvws/nl-covid19-data-dashboard#2703]
### Describe the bug, issue or concern
On the page https://coronadashboard.rijksoverheid.nl/landelijk/ziekenhuis-opnames, in the graph "Bezetting gewone ziekenhuisbedden (zonder IC-bedden) door de tijd heen" the date of the final data point is incorrect (25th of may i.p.v. 25th april). Looking at the source data from LCPS, it correctly shows the 25th of april

### Expected behavior
The final data point shows the correct date of the 25th of april

### Screenshots
![image](https://user-images.githubusercontent.com/37929570/115998230-92ddc280-a5e6-11eb-93a8-40e3719e0616.png)

**Desktop (please complete the following information):**
 - OS: openSUSE Tumbleweed, Kernel 5.11.15-1
 - Browser: Mozilla Firefox 
 - Version 87.0

### Additional context
N/A

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by wickyw** [comment]
This also seems to be the case for the IC occupancy count at https://coronadashboard.rijksoverheid.nl/landelijk/intensive-care-opnames:

![image](https://user-images.githubusercontent.com/37929570/115998501-d38a0b80-a5e7-11eb-925b-b829e964978c.png)

**Comment by VWSCoronaDashboard7** [comment]
Thanks for bringing this up. Team saw the same thing and this has been corrected!
