### ISSUE TITLE
Use logarithmic Y-axis on growth processes

### ISSUE THREAD

**Issue by htot** [minvws/nl-covid19-data-dashboard#2791]
By nature infections, deaths, hospitalizations show exponential growth or decay. Typically plotting this on linear scales easily leads to wrong conclusions on for instance effectiveness of government measures.

Plotting on a logarithmic Y-scale shows almost stunning clarity on effects of measures as growth or decays translate to straight lines. See [Our World in Data](https://ourworldindata.org/explorers/coronavirus-data-explorer?yScale=log&zoomToSelection=true&pickerSort=asc&pickerMetric=location&Interval=7-day+rolling+average&Relative+to+Population=true&Align+outbreaks=false&country=~NLD&Metric=Confirmed+cases) for an example.

**Comment by VWSCoronaDashboard7** [comment]
See comment on https://github.com/minvws/nl-covid19-data-dashboard/issues/2792
