### ISSUE TITLE
used colors of arrows on dashboard

### ISSUE THREAD

**Issue by rbwrk** [minvws/nl-covid19-data-dashboard#2838]
I think that the colors of the arrows used to illustrate the trend are used unclearly at this time.

The examples are on the index page.
https://coronadashboard.rijksoverheid.nl/

### Example 1

> **Aantal positieve testen**
> Gisteren (12 mei) zijn er 6.422 nieuwe positieve tests gemeld. Dat is lager dan ↓ [color:red] het gemiddelde van de afgelopen 7 dagen (6.604,4).

The down arrow is now red.
Less infections is actually positive.
Green usually means positive.
Maybe a green arrow is more obvious in this case.

### Example 2

> **Ziekenhuisopnames**
> Eergisteren (11 mei) zijn 265 nieuwe ziekenhuisopnames gemeld. Dat is hoger dan ↑ [color:blue] het gemiddelde van de afgelopen 7 dagen (216,7).

The up arrow is now blue.
More hospital admissions is not so good.
Red usually means 'not so good'.
Maybe a red arrow is more obvious in this case.

### Screenshots (made on 13 may 2021 ~ 12:30)

**Current colors:**
![coronadash-current-colors](https://user-images.githubusercontent.com/18292366/118115718-9bf1d080-b3e9-11eb-8d42-174c5e7c6f02.png)

**Obvious colors:**
![coronadash-obvious-colors](https://user-images.githubusercontent.com/18292366/118115728-a01dee00-b3e9-11eb-9217-f02453682695.png)

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard7** [comment]
Totally right! This bug must have snuck in when we switched to using 7-day averages for our differences. We've corrected it. The arrows are now blue or red again, as intended. Thanks for the report.
