### ISSUE TITLE
Last five weeks on graphs on mobile results in a blank page

### ISSUE THREAD

**Issue by thewouter** [minvws/nl-covid19-data-dashboard#2851]
### Describe the bug, issue or concern

When I browse the corona dashboard on mobile and I perform the following steps I get a blank page

### To Reproduce
1. Be on mobile 
2. Click on 'Aantal positieve testen'
3. Scroll to 'Aantal positieve testen per leeftijdsgroep door de tijd heen'.
4. Tap on the graph to get split data per age group
5. Tap somewhere else to get rid of the popup with info
6. Tap on 'Laatste vijf weken'
7. Be greeted with a blank page. 

### Expected behaviour
I expect to get the requested data in the last five weeks

### Screenshots
https://streamable.com/97ve0l   (video too large for GitHub)

**Desktop (please complete the following information):**
 - does not apply to desktop

**Smartphone (please complete the following information):**
 - Device: OnePlus 6T
 - OS: Oxygen OS 10.3.10
 - Browser: both chrome mobile and Firefox mobile
 - Version n/a

### Additional context
I think this has to do with the implementation of the touching or tapping or something. It is rather annoying because I often tap on the graph per accident and to fix it I have to go to a different web page, going back does not go back to the previous webpage.
I have observed this with several graphs but I couldn't record it reliably for other graphs

### Governance
- [ x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard7** [comment]
Has been fixed, thanks for the report!
