### ISSUE TITLE
Missing space on explanation for R0 value.

### ISSUE THREAD

**Issue by roberrrt-s** [minvws/nl-covid19-data-dashboard#2910]
### Describe the bug, issue or concern

There's a space missing on the R0 page between the change in R0 value from the last value until the current one.
E.g. 

### To Reproduce
1. Go to 'https://coronadashboard.rijksoverheid.nl/landelijk/reproductiegetal'
2. Click on 'not applicable'
3. Scroll down to 'Reproductiegetal'

### Expected behaviour
A space between "meer" and "dan"

### Screenshots
<img width="533" alt="Screenshot 2021-05-29 at 12 54 42" src="https://user-images.githubusercontent.com/6113643/120067664-132b9380-c07d-11eb-9cb9-8bed5c2a8384.png">

**Desktop (please complete the following information):**
- latest Mac OS
- latest Chrome
- all sizes

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by evroon** [comment]
Note that this happens on more pages than `Reproductiegetal`, also under `Ziekenhuisopnames`, `Intensive care-opnames`, `Besmettelijke mensen`, `Sterfte` and more. 

I tried to find the i18n strings in the repo, but could not find them and my guess is that they are stored in the database. That would mean it is not really a bug of this repo, but a mistake by someone who enters the strings on the front-end. But I'm not sure about that.

**Comment by roberrrt-s** [comment]
Yeah, I did some debugging, it does look good in this instance: https://github.com/minvws/nl-covid19-data-dashboard/blob/17b10d64f5281fabda1ac0a825a7c184c398cd22/packages/app/src/components/difference-indicator/tile-average-difference.tsx#L59 note the `{' '}`.

**Comment by evroon** [comment]
Ah I see what you mean, then I was wrong. It should be easy to resolve I guess.

**Comment by VWSCoronaDashboard10** [comment]
Thank you both 👍
