### ISSUE TITLE
Typo in FAQ 'niet komt niet overeenkomt'

### ISSUE THREAD

**Issue by martijnwijnands** [minvws/nl-covid19-data-dashboard#2951]
![Screenshot_20210608-015049_Chrome](https://user-images.githubusercontent.com/72670557/121101481-33d1b700-c7fc-11eb-85d3-fa513a2f6ea5.jpg)

**Comment by VWSCoronaDashboard7** [comment]
Thanks, forwarded it to the team responsible for updating that so it can get fixed.
