### ISSUE TITLE
Municipality Name Update

### ISSUE THREAD

**Issue by EgeSarii** [minvws/nl-covid19-data-dashboard#2993]
The bug is an instance update issue for municipalities. The bug is described in below parts with steps.

1. Go to corona dashboard site.
2. Click on Municipalities
3. Move the cursor to any municipality i.e. Nijmegen
4. Try to move the cursor to another city i.e. Eindhoven
5. The name does not change, even the cursor is on Eindhoven, it shows Nijmegen
6. This occurs in also the positive cases for municipalities, it continues to show Nijmegen's positive cases, even the cursor is on Eindhoven.
7. The only way to get rid of this, is start the process again : move the cursor outside of the map, then choose the city again.
8. But also in this case, you have to be fast otherwise, you can not choose the municipality you want, it assigns to a city that you have passed.
![Ekran görüntüsü 2021-06-12 17-54-08](https://user-images.githubusercontent.com/33198092/121781952-85d15e80-cba7-11eb-9afa-acce83c6c3ce.png)
HERE it shows Nijmegen when the cursor is on Nijmegen

![Ekran görüntüsü 2021-06-12 17-54-17](https://user-images.githubusercontent.com/33198092/121781961-98e42e80-cba7-11eb-8bea-3d4dcd101461.png)
Here it shows again Nijmegen but the cursor is not on Nijmegen

So the name and information of the municipality does not update until reset operation.

**Desktop (please complete the following information):**
 - OS: My current OS is Linux based Ubuntu 20.04 
 - Browser : I am using Chrome for Browser
 - Version : 91.0.4472.101 for Chrome Version

**Smartphone (please complete the following information):**
 - Device: Huawei Mate 20 Lite
 - OS: Android 10
 - Browser : Chrome
 - 
### Additional context
I love this corona dashboard. I am clicking it everyday and find it very useful especially for tracking vaccinations and positive cases. Also I am interested in the active cases and new positive cases in my city. I really want to contribute this project with my code, but unfortunately I don't know front-end. I hope the issue is clear and described well. I will be always available for further questions. My e-mail address is sariege323@gmail.com . I wish good luck to all contributers and developers.

Have a nice day!

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by EgeSarii** [comment]
I think it is done, because I have checked and now it updates. If it is done I going to close this issue. But can you confirm before-hand?

Also thank you everyone who helps, develops creates beautiful things good jobs like this.

**Comment by VWSCoronaDashboard** [comment]
@EgeSarii Glad it's fixed for you, since we tried a bunch of things but couldn't reproduce it even with deliberately strained systems (slow connections, 100x slower cpu etc). Must have been a fluke.. but thank you for the elaborate report. That really helps making things better.
