### ISSUE TITLE
Include overview of excess mortality in the dashboard

### ISSUE THREAD

**Issue by Koen1999** [minvws/nl-covid19-data-dashboard#3]
People may also be interested in excess mortality as an indicator.
For the overview to be useful, it should be easy to compare mortality of this year with previous year or an average of previous years.

The excess mortality includes people who were not tested or who passed away due to indirect consequences of COVID-19.

Data is available here: https://opendata.cbs.nl/#/CBS/nl/dataset/70895ned/table

**Comment by VWSCoronaDashboard** [comment]
Hi Koen. Thanks for the suggestion. The most important function of the dashboard is to provide “_early warning_” signals. Mortality and excess mortality rates don’t offer that and therefore haven’t been included in the dashboard.
