### ISSUE TITLE
Placeholder text "Onbekend - onbekend toelichting" present on main page.

### ISSUE THREAD

**Issue by Gamer1120** [minvws/nl-covid19-data-dashboard#3039]
### Describe the bug, issue or concern
Placeholder text "Onbekend - onbekend toelichting" present on main page.

### To Reproduce
1. Go to https://coronadashboard.rijksoverheid.nl/
2. Click on "Wat betekenen de vier risiconiveaus?
3. See error

### Expected behavior
This text is not present on the page

### Screenshots
![afbeelding](https://user-images.githubusercontent.com/9074448/122988621-3b6b9100-d3a2-11eb-9494-b42dcdb8564b.png)

**Desktop (please complete the following information):**
Windows 10, reproducible on Firefox, Edge, Chrome (see screenshot left to right)

### Governance
- [x ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard** [comment]
Thanks for the report, we've submitted a patch to remove.
