### ISSUE TITLE
Some titles not really visible on mobile devices

### ISSUE THREAD

**Issue by YannickMol** [minvws/nl-covid19-data-dashboard#3158]
### Describe the bug, issue or concern

Some of the page titles are not really visible on mobile devices.

### Expected behavior
A clear visibility of all page titles.

### Screenshots
![Screenshot_20210710-082027_Chrome.jpg](https://user-images.githubusercontent.com/13256289/125154042-3d7e6f80-e158-11eb-966e-b85e5416ead3.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20
 - OS: Android
 - Browser: Google Chrome
 - Version: 91

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard14** [comment]
This has been fixed! Thanks for letting us know.
