### ISSUE TITLE
Possibly markdown showing above vaccination willingness graph

### ISSUE THREAD

**Issue by wickyw** [minvws/nl-covid19-data-dashboard#3217]
### Describe the bug, issue or concern
Markdown formatting or something similar (\*\*Bold text\*\*) is showing rather than the formatted text itself(**Bold text**).

### To Reproduce
1. Go to [https://coronadashboard.rijksoverheid.nl/landelijk/vaccinaties](https://coronadashboard.rijksoverheid.nl/landelijk/vaccinaties)
2. Scroll down to the vaccination willingness graph.
3. See "\*\*Percentage van de Nederlandse bevolking van 16 jaar en ouder dat zelf een prik wil hebben of al heeft gehad\*\*".

### Expected behavior
Seeing "**Percentage van de Nederlandse bevolking van 16 jaar en ouder dat zelf een prik wil hebben of al heeft gehad**"

### Screenshots
![Screenshot_20210720_123809](https://user-images.githubusercontent.com/37929570/126311805-c7f612aa-05ab-47bb-97f4-7c58e14bf3c8.png)

**Desktop (please complete the following information):**
 - OS: OpenSUSE Tumbleweed
 - Browser Firefox
 - Version 89.0.2

### Additional context
N/A

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard7** [comment]
Thanks for the spot! We've asked the editors to remove the markdown syntax for that text.
