### ISSUE TITLE
Alert value for hospital admissionsvoor isn't scaled for municipalities/safety regions

### ISSUE THREAD

**Issue by markijbema** [minvws/nl-covid19-data-dashboard#334]
The alert value is always 40, even though these are absolute numbers, so the alert value for municipalities should either be scaled down, or not be shown.

Municipality of Amsterdam:
![image](https://user-images.githubusercontent.com/624143/93314132-ab445e00-f809-11ea-983a-046cb9d22b6b.png)

The Netherlands:
![image](https://user-images.githubusercontent.com/624143/93314181-bbf4d400-f809-11ea-9642-dee9b813f6e4.png)

### Governance
- [X] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [X] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [X] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard7** [comment]
Thanks for reporting this, it should not have been shown for the Municipality level and has been removed.
