### ISSUE TITLE
Suggestion: add additional GGD testing measurements

### ISSUE THREAD

**Issue by tkon99** [minvws/nl-covid19-data-dashboard#339]
### Describe the bug, issue or concern

I saw the new PR #338 and was wondering whether further expansion would be possible and whether it is already being looked at internally.

I think it would be very helpful to see the number of hours between test and result as a proxy for test capacity, this could be on a moving average (last three days) basis.

Extending this, a direct test availability could also be included, say X% of spots taken in the next 2 days (or however far ahead GGD can plan appointments for now).

Both of these could be included on the regional/municipal level as well, if available.

### Governance
- [X] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [X] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [X] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard7** [comment]
Hi. We've upstreamed the suggestion to the data team per their consideration. There are many possible indicators that are being looked at so we can't say if or if so when this would be included. Closing this issue in the meantime since there's no further forward action at the moment.
