### ISSUE TITLE
Suggestion: Make clear which version/build/commit is published

### ISSUE THREAD

**Issue by RvMouche** [minvws/nl-covid19-data-dashboard#350]
### Describe the bug, issue or concern

It's pretty interesting to follow along with the commits in this repro; but it can be hard to clearly identify which version, build or commit is published on coronadashboard.government.nl / coronadashboard.rijksoverheid.nl.

### To Reproduce
N/A

### Expected behavior
Being able to find out which commit, build of version is published. Possible right under the last updated string, as a comment up top in 'view source'-pannel or by calling a JS-function.

### Screenshots
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

### Additional context
N/A

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard7** [comment]
We're already publishing the commit hash as a meta key in the HTML source. For example:

`<meta name="version" content="5a78287"/>`
