### ISSUE TITLE
Unexpected vaccination percentages

### ISSUE THREAD

**Issue by jorritolthuis** [minvws/nl-covid19-data-dashboard#3536]
### Describe the bug, issue or concern
The total percentage of people (18+, but the exact same problem occurs for 12+) vaccinated is 81.7% (data of Sep 13, [see "Vaccinatiegraad"](https://coronadashboard.rijksoverheid.nl/landelijk/vaccinaties)). However, the highest percentage in any of the veiligheidsregios is 76% ([Drenthe, see "Vaccinatiegraad"](https://coronadashboard.rijksoverheid.nl/veiligheidsregio/VR03/vaccinaties)).

I believe the total percentage of people vaccinated cannot be higher than the highest value in any of the regions that make up this total.

### To Reproduce
1. Go to https://coronadashboard.rijksoverheid.nl/landelijk/vaccinaties
2. Note the percentage at "Volledig gevaccineerd" in the "Vaccinatiegraad" section. Either do this for 12+ or 18+.
3. Scroll down to "Vaccinatiegraad per gemeente"
4. Select "18 jaar en ouder" or "12 jaar en ouder" depending on what you did for step 2.
5. Select "Per veiligheidsregio"
6. For each of the regions: Hover the mouse over it, and note the percentage behind "volledig gevaccineerd" (note: _not_ the value in bold)
7. Compare the percentage of each of the regions to the total from step 2.
8. Conclude that the total percentage is significantly higher than for any region.

### Expected behaviour
The total percentage of vaccinated people should be less than the percentage in the most vaccinated region, and it should be more than the percentage in the least vaccinated region.

### Screenshots

Total percentage of people (18+) fully vaccinated:
![Screenshot 2021-09-19 at 15 54 34](https://user-images.githubusercontent.com/28347783/133931415-3660295a-e785-4f15-9bca-b0a48783aecf.png)

Percentage of people (18+) fully vaccinated in each of the veiligheidsregios:
![vaccination-per-region](https://user-images.githubusercontent.com/28347783/133931823-a2538ec1-ced4-42ec-8b05-eee6156df153.png)

**Desktop:**
 - OS: macOS
 - Browser: Safari
 - Version: 14.1.2

### Additional context
* The data of each of the regions is obtained on Sep 12, whereas the country-wide data is obtained on Sep 13. However, a difference of 5.7 percentage points is much more than what can be explained.
* I realise some discrepancies may occur since not every region has the same number of citizens, though the total percentage should not be able to be higher than the percentage in the highest region.
* I do not know if this difference originates from the source data, or from some processing steps.

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard7** [comment]
Hi, thanks for reaching out. The explanation for this is outlined in the data explanation page, I'll copy the most relevant snippet here and link to the rest:

> RIVM bases its figures on the total national vaccination coverage on the calculated number of doses administered. This is because the reported vaccinations in the registration system CIMS were not complete enough earlier. As the vaccination coverage is partly based on calculations, the actual coverage may be slightly different.

> The figures for vaccination coverage by age group and vaccination coverage per municipality come from CIMS. RIVM registers in CIMS how many people have started and how many people have completed their vaccinations.

Please make sure to review the section _'Vaccination coverage by age group and per municipality actually higher'_ and the four reasons why to get the full picture. Amongst other things, it mentions that "CIMS only lists the vaccinations given to people who have given permission to register their vaccination."

English version: https://coronadashboard.government.nl/verantwoording#vaccinatie
Dutch version: https://coronadashboard.rijksoverheid.nl/verantwoording#vaccinatie
