### ISSUE TITLE
Dynamic legend range in maps

### ISSUE THREAD

**Issue by aptroost** [minvws/nl-covid19-data-dashboard#3791]
### Describe the bug, issue or concern
At the landelijk/positief-geteste-mensen page, the 'Aantal positief geteste mensen per gemeente of veiligheidsregio' page has a map. This map has a legend value ranging between 0 and 30. This value is much larger in certain 'gemeentes' and therefore it does not give a clear overview. 

### To Reproduce
Go to Link to page [https://coronadashboard.rijksoverheid.nl/landelijk/positief-geteste-mensen](https://coronadashboard.rijksoverheid.nl/landelijk/positief-geteste-mensen)

View the following map:
![map-besmettingen](https://user-images.githubusercontent.com/23358229/140732557-e0442ef9-e665-4c97-83ac-f6e3e170f50f.png)

A summary of all 'gemeentes' with different expected tints are as follows:
| Gemeente  | Value per 100k 'besmettingen' | Diagnosed tint of blue | Expected tint of blue |
| ------------- | ------------- | ------------- | ------------- |
| Westvoorne  | 6.7  | + | + |
| Oirschot  | 15.9  | ++ | ++ |
| Meppel  | 29.1  | +++ | +++ |
| Ouder-Amstel  | 35.4  | ++++ | ++++ |
| Alblasserdam  | 139.1  | ++++ | +++++ |
| Urk  | 334.5  | ++++ | ++++++ |

Table based on the data last updated on 07 Nov 2021.

All 'gemeentes' with a value > 30 will turn dark blue. The image on this page will therefore give an unclear overview of the actual situation.

### Expected behaviour
The expected behaviour can be seen in the last column of the table above.

Thorough fix:
- Dynamic maximum range based on the values with a minimum range of 0-30 as is now. This can vary over time since readers view tints instead of colours. Therefore the tints can be dynamically assigned to values on a temporal scale.

Easy/Quick fix:
- Logarithmic static legend (0, 1-9, 10-99, 100-999, etc.)
- Nicer; Something in between (0, 1-4, 5-19, 20-49, 50-99, 100-249, 250-999, etc)

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

### Additional context
N/A

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard7** [comment]
Hi, thanks for the suggestion and elaborate write-up. We're aware of this behaviour and as mentioned in #3717 it's expected behaviour. It's been marked for review and options like the ones you mention are being considered, along with their various trade-offs.
