### ISSUE TITLE
Feature request: show daily trend for both Hospital and ICU admissions

### ISSUE THREAD

**Issue by ArthurHNL** [minvws/nl-covid19-data-dashboard#3810]
Just like the daily trend that is currently shown for confirmed cases ("groeigetal"), I think it would be nice to see this graph for hospital admissions and ICU admissions.

### Governance
- [ X ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ X ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ X ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard7** [comment]
Hi, thanks for the suggestion. It's best to reach out via the [contact page of the dashboard](https://coronadashboard.rijksoverheid.nl/contact) for suggestions like these.
