### ISSUE TITLE
Re-introduce number of daily positive tests on the front page

### ISSUE THREAD

**Issue by abspoel** [minvws/nl-covid19-data-dashboard#3851]
### Describe the bug, issue or concern

The daily number of positive tests is the most current indicator of the present situation regarding the spread of the coronavirus. This number used to be present on the front page of the dashboard, but now it needs at least two clicks (on my small screen mobile: 3 clicks and 2 scroll-downs) to access it.

The numbers that *are* currently present are not very relevant nor easy to digest. Two of the numbers currently displayed on the front page (daily IC/hospital inflow of COVID patients) are basically related to the number of positive tests two weeks in the past. The third number, the vaccination rate, increases only very marginally over time.

### Expected behavior

Re-introduce the number of daily positive tests on the front page.

Additionally, it can be helpful to add the total number of IC/hospital beds occupied due to COVID next to the daily inflow, to better gauge the current pressure on the healthcare system.

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard7** [comment]
Hi, thanks for the suggestion. It's best to reach out via the [contact page of the dashboard](https://coronadashboard.rijksoverheid.nl/contact) for suggestions like these.
