### ISSUE TITLE
Locale files missing unless you have access to CMS

### ISSUE THREAD

**Issue by boisei0** [minvws/nl-covid19-data-dashboard#3927]
### Locale files have been removed from the repository
As of PR #2504, Lokalize is handled through Sanity, which requires logging in to the CMS. Additional to that, the `export_{nl,en}.json` files have been removed from the repository and were instead added to the .gitignore. 
While this improves the repository a lot with the lack of constant Lokalise pushes, it comes with a couple concerns. 

1. The general public can no longer clone this repository and build it as-is. A connection the the CMS is needed, for the locale files to be downloaded using the "lokalize export tool" located in the CMS part of this repository: https://github.com/minvws/nl-covid19-data-dashboard/blob/232fe630baa7781ae1b2a55666a53b998fb1eb0a/packages/cms/src/lokalize/export.ts
2. Accountability: when new data is added to the dashboard, but is still in development and haven't been standardised in the data export yet, it is often added to the locale files. This has, for example, previously happened with vaccination data a year ago, and in the early days of this project with constants as well, before they were defined elsewhere. This is currently happening with the data on boosters being administered.

To expand on point 2, the vaccinations page of the dashboard is displaying information on boosters administered. The source of this data is listed as RIVM, but differs from the numbers released on a weekly base in the epidemiological reports. For day to day updates, the dashboard is the most reliable source of information. 

https://github.com/minvws/nl-covid19-data-dashboard/blob/232fe630baa7781ae1b2a55666a53b998fb1eb0a/packages/app/src/domain/vaccine/vaccinations-booster-kpi-section.tsx#L32

As above line shows, the current data for booster vaccinations administered is retrieved from the locale files. To monitor historical values of this data, changes on the locale file should be monitored, or once added to the data JSON files, those can be monitored instead. At the moment, this set of data can only be viewed on the dashboard itself, or scraped every day to monitor for changes. For historic observations, this creates an unwanted situation as this can't be verified. That is beyond the unwanted need to scrape a website for data that previously was included in this repository itself.

While I understand that the data schemes have to be verified before they can be released in the schemes itself, and adding them to the locale gives a good temporary solution, however when the locale files itself can only be viewed when having access to the CMS, this creates a situation where it's impossible to verify the integrity of the data that is already released on the dashboard while not added to the public facing JSON files of the project. Additionally, the statistics itself has not yet been released by the RIVM as open data, which again makes it harder to monitor the integrity of the data. An easy way to resolve some of that, would be by releasing the locale files again.

### To Reproduce
As this is an issue with the repository structure and data committed, see the above as a base.
1. Clone the repository
2. Try to set up the project without having access to the CMS, and thus not logged in to Sanity.
3. Watch the Lokalize export tool fail while not logged in.
4. Watch how the typescript fails to compile because of the missing `export_nl.json` and `export_en.json files`

### Additional context
I wrote this with a fever caused by said booster vaccination, apologies for unclear sentences. 

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard18** [comment]
Hi @boisei0,

Thanks for pointing that out. Our apologies for not replying earlier. Because of a lot of releases passed since this issue seems no longer relevant. In the repository, instructions can be followed to set up the project with Lokalize texts without a Sanity login. 
Here is a link to the corresponding instructions:
https://github.com/minvws/nl-covid19-data-dashboard/tree/develop/packages/app#configure
