### ISSUE TITLE
Omikron variant shown at top of graph instead of bottom

### ISSUE THREAD

**Issue by osirisinferi** [minvws/nl-covid19-data-dashboard#3959]
### Describe the bug, issue or concern

All the previous variants were "building up" from the bottom of the graph, pushing the older variants away at the top. I.e.: the alpha variant was a few percent above 0 % until it started building up to 25 % (from the bottom), pusing away the other variants at the top. However, the omikron variant is now displayed from 100 % to 81,8 % (at the top). This is weird and not comparible with the other variants.

### To Reproduce
1. Go to https://coronadashboard.rijksoverheid.nl/landelijk/varianten
2. Scroll down to 'Varianten van het coronavirus door de tijd heen'
4. See graph and notice the difference of build up of the variants compared to the omikron variant.

### Expected behavior
Omikron variant also building up from 0 % to (now) 8,8 % (from the bottom up) instead of from 100 % to 81,8 % (from the top).

**Desktop (please complete the following information):**
 - OS: Gentoo GNU/Linux
 - Browser: Chromium
 - Version: 89.0.4389.114.

### Governance
- [X] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [X] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [X] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by simonbesters** [comment]
In addition to this issue. The graph on that page shows the prevalence of Omikron (3.8%) in januari 2021, but it is only discovered in november 2021. That seems incorrect.

![Schermafbeelding 2022-01-14 om 16 46 41](https://user-images.githubusercontent.com/45492066/149544376-c5ad01da-3826-46c0-aeea-12eaba7ec585.png)

**Comment by osirisinferi** [comment]
Seems to be fixed.
