### ISSUE TITLE
positief-geteste-mensen choropleth needs more colors

### ISSUE THREAD

**Issue by MarByteBeep** [minvws/nl-covid19-data-dashboard#3967]
When observing the positively tested people choropleth:

https://coronadashboard.rijksoverheid.nl/landelijk/positief-geteste-mensen

all is an equal shade of blue, because of the high infection rates at the moment. This makes it hard to see where the differences between regions are. Tubbergen has 400+, and Texel has 90+. This is a massive difference, yet everything over 30+ uses the same color.

Please use a different scale based on actual infection rates, or add more colors to accommodate for the current high infection rates.

**Comment by osirisinferi** [comment]
Isn't it possible to make a *dynamic* colour scale?

**Comment by VWSCoronaDashboard19** [comment]
Closing this issue as it has recently been fixed by our dev team. Thank you for your alertness.
