### ISSUE TITLE
Remove reproduction number estimate; it's inaccurate

### ISSUE THREAD

**Issue by EwoutH** [minvws/nl-covid19-data-dashboard#410]
On September 15th the Dashboard was updated with RIVM data, stating that the reproduction number would be in the confidence interval between 0,92 and 1,07 on September 4th.
<img width="600" alt="Screenshot_223" src="https://user-images.githubusercontent.com/15776622/93901521-e3124080-fcf6-11ea-9097-c82ce7e43563.png">

Today (September 22th) the reproduction number was updated for September 4th: 1,33, with the confidence interval ranging from 1,26 to 1,40. Nowhere near the predicted confidence interval.
<img width="600" alt="Screenshot_224" src="https://user-images.githubusercontent.com/15776622/93901523-e3aad700-fcf6-11ea-9c0d-9a4a2f2a0955.png">

A downward bias toward recent data can be seen for several weeks. This is heavily misleading, since it suggests it's going for all dates for which an effective R isn't calculated yet.

Aside from removing it from the dashboard, I would also heavily recommend upstreaming this issue to the RIVM to improve their data calculation, or at least be more honest about the vast uncertainty of these estimates/predictions.

**Comment by EwoutH** [comment]
@VWSCoronaDashboard Could you (assign someone to) review this issue?

**Comment by VWSCoronaDashboard** [comment]
> @VWSCoronaDashboard Could you (assign someone to) review this issue?

Hi! We've seen this issue. As it's not a technical issue but a strategic one, responding to this is going to take a bit longer. Sorry about that.

**Comment by VWSCoronaDashboard7** [comment]
@EwoutH We monitor all issues but cannot always reply immediately. This question is not a technical issue but rather a question about data. We have therefore reached out to the RIVM on your behalf to ask for an explanation of the deviation you mention. Here's the response:

> Het reproductiegetal (R-waarde) wordt geschat op basis van de trend in het aantal meldingen. Hoe sneller het aantal meldingen oploopt, hoe hoger het geschatte reproductiegetal dus is. De rapportagevertragingen en de tijdsduur tussen opeenvolgende infecties betekenen in Nederland dat we alleen betrouwbare schattingen kunnen maken van het reproductiegetal, voor langer dan 14 dagen geleden.
> 
> De genoemde onzekerheidsmarge is een 95% betrouwbaarheidsinterval. Dat wil zeggen dat het geschatte reproductiegetal met 95% zekerheid binnen die marge ligt. Dit is echter niet 100% zeker, het kan dus gebeuren dat de uiteindelijke schatting hierbuiten valt.

Hopefully this answers some of your questions. More about the R-value and how it is calculated can be found in the epidemiological rapport of the RIVM ( https://www.rivm.nl/documenten/wekelijkse-update-epidemiologische-situatie-covid-19-in-nederland ) at pages 29 and 30.

There is currently no intention to remove the reproduction number from the dashboard. We do appreciate the feedback and case example and will take that into consideration when thinking about how to explain R-value related data as clear as possible.

**Comment by OnixGH** [comment]
@VWSCoronaDashboard7 the RIVM response states that: "[..] we are only able to make reliable R estimates for 14 days ago and before".

In other words, the estimates for the past 14 days are *not* reliable, which I believe is the issue @EwoutH raised that IMHO still stands.

Technically speaking, the dashboard acknowledges this unreliability by not plotting R for this period (and mentions that in the legend), but at the same time the 95% CI around the R is still plotted, which effectively means you are still using the unreliable R.

I would also suggest removing the 95% visualization of the past 14 days, or at the very least visually changing it to be clearly different from the 95% CI of >= 14 days ago, which IS based on a reliable estimate of R.

**Comment by EwoutH** [comment]
@VWSCoronaDashboard7 Thank you for your response. @OnixGH is right, the issue is that the 95% estimates for the past 14 days are not reliable and should therefore not be displayed on the dashboard.

So my suggestion would be:

- Do show the part of the graph for which an effective R is calculated.
- Do _not_ show the part of the graph for which only a 95% interval is given.

<img alt="R-dashboard" src="https://user-images.githubusercontent.com/15776622/94478997-61c61c80-01d4-11eb-860a-b262d29ac5b0.png">
