### ISSUE TITLE
Recente gebeurtenissen missen onder grafieken

### ISSUE THREAD

**Issue by basst85** [minvws/nl-covid19-data-dashboard#4134]
Onder de grafieken missen in de balk "Uitgelichte gebeurtenissen" de meest recente gebeurtenissen. 
Denk hierbij aan de laatste versoepelingen van 25 februari en 23 maart.

**Comment by VWSCoronaDashboard19** [comment]
Thanks for this issue basst85. Can you send your findings to coronadashboard@minvws.nl, so our team can look into in-depth data and why it's missing?
