### ISSUE TITLE
Gemeentes not opening on Android Chrome

### ISSUE THREAD

**Issue by mechoriet** [minvws/nl-covid19-data-dashboard#421]
### Describe the bug, issue or concern

The Gemeentes map doesn't work like it should on Android Chrome,
it should send you to the page where you can see all the statistics from that specific "Gemeente" like on Windows Chrome

### To Reproduce

- go to "coronadashboard.rijksoverheid.nl" on android Chrome
- click on "Gemeentes"
- then try to click a "Gemeente" it doesn't matter which one you click it seems to happen to all of them
- it normally should show the statistics of that "Gemeente" but it stays on the selector map but it only highlights them and shows there tooltip

### Screenshots
![image](https://user-images.githubusercontent.com/4313219/94050982-3fe52800-fdd7-11ea-9daa-c7edcfe5fd5f.png)
^ desktop

![Screenshot_20200923-150422_Chrome](https://user-images.githubusercontent.com/4313219/94051031-4a072680-fdd7-11ea-8536-9eea768712dc.jpg)
^ mobile(Android - Chrome)

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Browser Chrome
 - Version 85.0.4183.102

**Smartphone (please complete the following information):**
 - Device: Galaxy S20+
 - OS: Android 10
 - Browser Chrome
 - Version 85.0.4183.120

### Additional context
hopefully its clear enough

### Governance
- [ ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard** [comment]
@mechoriet Can you try clicking on the tooltip?

Any screen that's "small" requires a click on the tooltip to switch to a municipality. It's different behavior from larger screens, so I understand the confusion.

**Comment by VWSCoronaDashboard** [comment]
Assuming the tooltip was the issue and no further action is required. If clicking the tooltip does not solve the issue for you, please open another ticket.
