### ISSUE TITLE
Inconsistent naming in time span selection for graphs ("laatste" vs. "afgelopen")

### ISSUE THREAD

**Issue by leonoverweel** [minvws/nl-covid19-data-dashboard#4298]
### Describe the bug, issue or concern

All time spans use "Afgelopen..." except 30 days, which uses "Laatste..." as you can see here:

<img width="872" alt="image" src="https://user-images.githubusercontent.com/7980521/174736952-44853ac4-7faf-4f56-9e69-252fc4dea26f.png">

### To Reproduce
1. Go to https://coronadashboard.rijksoverheid.nl/landelijk/rioolwater
2. Click on 'Toon alles'
4. See naming inconsistency

### Expected behavior

All time spans should use "Afgelopen..."

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard24** [comment]
Hi @leonoverweel, thanks for your feedback! We will update the text and it should be visible somewhere in the next couple of days.
