### ISSUE TITLE
Normeer huisartsen van week naar dag

### ISSUE THREAD

**Issue by Sjors** [minvws/nl-covid19-data-dashboard#43]
De meeste gegevens, zoals het aantal positief geteste patiënten, zijn per dag, per 100.000 inwoners: 
<img width="379" alt="Schermafbeelding 2020-07-02 om 21 51 50" src="https://user-images.githubusercontent.com/10217/86403572-44091a00-bcae-11ea-8ac6-8c2031d4af1f.png">

Maar het "Aantal patiënten waarvan huisartsen COVID-19 vermoeden" is per week, per 100.000 inwoners:
<img width="389" alt="Schermafbeelding 2020-07-02 om 21 51 36" src="https://user-images.githubusercontent.com/10217/86403613-57b48080-bcae-11ea-8b83-1a6af572575b.png">

Het is beter om die schatting door 7 te delen, zodat het per dag is.

Daarnaast is het zinnig om uit te leggen hoe die twee zich met elkaar verhouden. 117 / 7 = 16 per dag, terwijl 0.4 mensen positief getest zijn. Een oplettende lezer zal zich dan afvragen of huisartsen er een factor 40 naast zitten in hun inschatting, of dat er iets anders speelt.

Tot slot is het ook niet heel duidelijk verwoord of het hier alleen om alleen nieuwe verdachte gevallen gaat.

**Comment by VWSCoronaDashboard** [comment]
Hoi Sjors, dank voor je suggestie.

Op het dashboard worden de cijfers uit de wekelijkse rapportage van het Nivel getoond. Omdat we deze niet op dag maar op weekbasis krijgen aangeleverd geven we deze ook op weekbasis weer. Omrekenen daarvan zou een onjuist beeld kunnen overbrengen van de situatie en de actualiteit van de gegevens. Als de gegevens op dagbasis beschikbaar komen zullen we deze op die manier opnemen.
Het getal 117 moest overigens 11,7 zijn. Dit heeft door een bug kort op het dashboard gestaan. Het is dus verhouding 1 op 4, wat een stuk logischer is.
