### ISSUE TITLE
Weekly summary should not contain thermometer position

### ISSUE THREAD

**Issue by hughrawlinson** [minvws/nl-covid19-data-dashboard#4953]
### Describe the bug, issue or concern

The weekly summary on the homepage contains the text "The Corona thermometer position is 1 Low". This is misleading since when you click through to the corona thermometer page, it's mentioned that the thermometer has not been updated since September 2022. If the thermometer is not in use anymore, an out of date value should not be presented to the user absent the context in which that value was calculated.

### To Reproduce

1. View the homepage
2. Observe the corona thermometer value in the weekly summary

### Expected behavior

The information in the weekly summary card should accurately summarize the week, and not contain outdated data from discontinued measurements.

### Screenshots

![Screenshot of the weekly summary card on the homepage containing the invalid corona thermometer data](https://github.com/minvws/nl-covid19-data-dashboard/assets/829836/8bd81def-9bd1-4d8c-8f3a-3ba858af92f2)

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by dvanzuijlekom** [comment]
Hi Hugh,

Thank you for your report and apologies for the long time it took to respond to your issue. The Product Owner of the Corona Dashboard has asked to relay the following message as an official response to your report:

> Due to the current calm state, the RIVM Response-team is no longer meeting to assess and discuss the situation and to determine whether or not the thermometer should be adjusted.
>
> The last time the state of the thermometer was determined was on June 6th 2023 and this state is still valid/current.
>  
> When/if the situation changes, for example due to a sudden upswing of the virus, it will be decided if the Response-team needs to get together again. When they do, they will decide on the state of the thermometer.

The text above is my translation of their original message in Dutch, which was the following:

> Door het rustige beeld komt het Responsteam van het RIVM niet meer bijeen om de situatie te bespreken en de stand van de coronathermometer te bepalen. Hierdoor wordt de thermometer niet meer aangepast.
>
> Op 6 juni 2023 is de stand van de thermometer voor het laatst bepaald, deze stand geldt nog steeds.
>
> Als de situatie verandert, bijvoorbeeld als het virus opleeft, wordt besloten of het Responsteam bij elkaar moet komen. Als het Responsteam samenkomt wordt de stand weer vastgesteld.

I hope this answers your concern.
