### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by breyten** [minvws/nl-covid19-data-dashboard#5]
Is there something like a roadmap? Because you're busy on other stuff, and having some sort of list of what's coming will prevent multiple issues about the same thing :)

**Comment by VWSCoronaDashboard** [comment]
We are working on it. this is definitely part of the plan!

**Comment by RdeWilde** [comment]
I think we can at least delete this one by now ;-)
https://github.com/minvws/nl-covid19-data-dashboard/projects/1

**Comment by breyten** [comment]
That seems about right :-)
