### ISSUE TITLE
Missing header 'verpleeghuizen'

### ISSUE THREAD

**Issue by pbruins84** [minvws/nl-covid19-data-dashboard#519]
### Describe the bug, issue or concern

The last three graphs on the left side of the homepage don't have their own header, but are a part of 'Vroegsignalering'.
The last three graphs should have have their own header, something like 'verpleeghuizen'

### To Reproduce
1. Go to https://coronadashboard.rijksoverheid.nl/
2. Scroll down.

### Expected behavior
The last three graphs should have have their own header, something like 'verpleeghuizen'

### Screenshots
![image](https://user-images.githubusercontent.com/5555752/94898085-3ae83e80-0491-11eb-90a6-12e8b87f8bcc.png)

**Comment by VWSCoronaDashboard7** [comment]
Thanks for the spot! We've added the missing string back in the locale files, it will be fixed with the data update later today.
