### ISSUE TITLE
Hospital admission signal and history are not up-to-date

### ISSUE THREAD

**Issue by Arnold-n** [minvws/nl-covid19-data-dashboard#544]
The hospital admission signal seems to be (and remain) outdated.

### Expected behavior

My understanding is that the hospital admission signal is based on the information of "bewezen Covid-19 opnames op de verpleegafdeling" as maintained by the stichting NICE.

The reason that this signal is outdated is likely that a snapshot is made only once, when the data for the most recent 3 days is still very incomplete (due to administration and/or due to later confirmation of suspected diagnosis).

For example, the hospital admission is currently 121, 81, and 111 for October 3-5, whereas the dashboard currently shows an average of only 55.3.

The result is a huge underrepresentation which is also very sensitive to administrative delays which may for example be different on different days of the week.

Not only is the signal itself outdated, the history graph is also based on these outdated signals and not updated based on the true underlying hospital admission information. The dashboard graph is relatively flat whereas the real curve on the stichting NICE website shows a very different curve.

### Screenshots

![image](https://user-images.githubusercontent.com/48472227/95263548-3b385f00-082e-11eb-9aff-63746c05f41d.png)
![image](https://user-images.githubusercontent.com/48472227/95263605-53a87980-082e-11eb-96e8-ea62948694a3.png)
![image](https://user-images.githubusercontent.com/48472227/95263648-658a1c80-082e-11eb-8040-7605c880fcb5.png)

### Risk

The risk is that it the dashboard underrepresents the actual status. As essential decisions are to be made on this signal, it's a different kind of security vulnerability.

### Governance
- [X] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [X] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [X] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard7** [comment]
Hi! Please see https://coronadashboard.rijksoverheid.nl/verantwoording for the explanation behind this data source. In short, we're using RIVM data here at the moment not the Stichting NICE dataset. Closing this issue because it's based on an erroneous assumption.
