### ISSUE TITLE
Cosmetic: Disable text selection when dragging readings in graphs

### ISSUE THREAD

**Issue by fvdm** [minvws/nl-covid19-data-dashboard#564]
### Describe the bug, issue or concern

When you slow drag/swipe the readings horizontally in a line graph on a smartphone, it can activate default dragging behavior of the browser. It wants to select the text of the graph.

### To Reproduce
1. On a smartphone (iPhone) go to the Corona Dashboard.
2. Find a line graph with text inside, such as 'Verloop over tijd'. 
3. Slowly (elder-mode: 1 sec per stop) touchdrag the cursor to another stop.
4. Sometimes the nearby text is selected and the context pop-up (copy, share) appears.

### Expected behavior
No text is selected while dragging over the graph.

I don't know much about web UI, but I believe there is a CSS prop to cancel text selection.

### Screenshots
![image](https://user-images.githubusercontent.com/93784/95630156-a168f000-0a81-11eb-9dfd-1a5659a5c9ce.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 14.0.1
 - Browser: Safari
 - Version: 14

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard7** [comment]
Hello! Excellent suggestion, we'll put this on our list of items to fix and will keep this open until resolution.

**Comment by MikeVerhees** [comment]
I did some testing and this seems to happen only on iOS.
When I tried preventing this from happening using `-webkit-user-select: none;` more unexpected stuff happens as it will just select the closest text it can find instead.

**Comment by VWSCoronaDashboard7** [comment]
Closing this, as commented above it's rather tricky to get reliable. It's still on our backlog but we likely won't invest more time in it because the gains are relatively small here.
