### ISSUE TITLE
Dashboard shows no indication/warning when data is outdated

### ISSUE THREAD

**Issue by joostjager** [minvws/nl-covid19-data-dashboard#60]
The top of the page shows the last update time ("Laatst bijgewerkt: 15:01, 13 juli 2020"). This inspires confidence that all data shown is up to date. This however does not seem to be the case. For example at the time of writing, the last update of the (apparently weekly) 'rioolwatermeting' is June 22, which is three weeks ago.

This is potentially dangerous for people basing their decisions on dashboard data without expanding each panel and checking the last update time.

Suggestion for fix: add a warning icon or color to each panel to signal when data hasn't been updated recently. The definition of 'recently' can differ for each panel (daily, weekly).

**Comment by VWSCoronaDashboard** [comment]
Hi Joost, thanks for reaching out. The dashboard shows the latest data available for each card. So when the dashboard was last updated, for "rioolwatermeting" the latest datapoint was June 22nd. We mention this recency in the bottom left of each card.

That said conveying the time interval can indeed be improved. This is on our short-term improvements list.

**Comment by joostjager** [comment]
Yes, so the point of this issue is that the user needs to expand every panel to check that last update date. It isn't visible otherwise:

![image](https://user-images.githubusercontent.com/4638168/87418555-299a3f00-c5d2-11ea-8afc-1be7da00a348.png)
