### ISSUE TITLE
Total number of tested individuals for a security region is incorrect

### ISSUE THREAD

**Issue by ArthurHNL** [minvws/nl-covid19-data-dashboard#627]
### Describe the bug, issue or concern

As seen in the image screenshot, according to the dashboard, in 'Brabant-Noord', 1249 persons were tested the past week of which 13.55% was positive (the header in the left card implies that this number contains both positive and negative tests). However, on the left, the total number of persons is 9220. I would suggest either making it more implicit that the left card shows the total number of tests that were positive or make the card on the left show the actual number of tested persons.

### To Reproduce
1. Go to <https://coronadashboard.rijksoverheid.nl/veiligheidsregio/VR21/positief-geteste-mensen#ggd>.

### Expected behavior
As I described above, either a header that makes it clear that these are the positive cases or the total number of tests displayed in the left card.

### Screenshots

![image](https://user-images.githubusercontent.com/31919595/95989578-c0bd9f80-0e2a-11eb-9a73-539173d8c467.png)

**Desktop (please complete the following information):**
Probably irrelevant but I'll still include it:
 - OS: Windows 10
 - Browser Firefox
 - Version 81.0.2

### Additional context
None

### Governance
- [X] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [X] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [X] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard7** [comment]
Hi! Thanks for the elaborate report. The wrong value was used for the left card, it should indeed have been the total number of tests by the municipal health services (GGD) in one week. This has been corrected.
