### ISSUE TITLE
Number of positive tests reports net increase per day, but not gross number of new positive tests per day

### ISSUE THREAD

**Issue by mzelst** [minvws/nl-covid19-data-dashboard#67]
Hi!

I noticed that the dashboard reports the number of new positive tests per day and describes this as "Dit getal laat zien van hoeveel mensen gisteren per 100.000 inwoners gemeld is dat ze positief getest zijn en COVID-19 hebben." 

However, the number on the dashboard is actually the net increase of positive tests per day. For example, the gross number of positive tests on July 15 is 117 while there are also 11 corrections for earlier days, leading to a net increase of 106. The discrepancy is even larger for July 14, as the net increase was 53 while the gross increase was 97 (and 44 corrections for earlier days). The description of this indicator is therefore not completely accurate in my opinion. Also, it might be better to actually report the gross increase of positive tests per day as it provides a more current indicator of the current dynamics of the infection rate.

Would you consider either changing the description or preferably, report both gross and net increase?

Thank you for your consideration!

Marino van Zelst

**Comment by VWSCoronaDashboard** [comment]
Hi Marino,

Thanks for reaching out. We’re using RIVM data and a calculation method they’ve provided (and checked) to derive these numbers. The number of positive test reports as currently displayed on the dashboard is the best representation for the total number of positive test reports . We’re working on further improvements to make this more suitable for ‘early warning’ purposes and will take your feedback on this into account.

**Comment by edwinveldhuizen** [comment]
> The number of positive test reports as currently displayed on the dashboard is the best representation for the total number of positive test reports
I guess you didn't get the point that was made. For the total I agree, this is the best representation, but you are not showing the total (52.073). Since most of those corrections are from March and April, it doesn't make much sense to extract them from today's total and the rivm didn't do either in their last daily tweets

**Comment by VWSCoronaDashboard7** [comment]
The dashboard now uses https://data.rivm.nl/covid-19/COVID-19_aantallen_gemeente_per_dag.csv which addresses this issue. See https://coronadashboard.rijksoverheid.nl/verantwoording for more information.
