### ISSUE TITLE
Suggestion: Heatmap is currently badly representing the amount of infections

### ISSUE THREAD

**Issue by annedeg** [minvws/nl-covid19-data-dashboard#805]
### Describe the bug, issue or concern

Currently the heatmap (choropleth map) is currently showing different colors between 0 and 30 infections per 100.000 people even though there are places with 100+ infections per 100.000 people.

I suggest using a scale between 0 and 100 to better represent the data in the choropleth map.

### To Reproduce
1. Go to https://coronadashboard.rijksoverheid.nl/landelijk/positief-geteste-mensen 
2. Scroll to "Distribution of confirmed cases in the Netherlands"

### Expected behavior
I would expect the map to at least use color changes for the distribution between 0 and 100+ cases instead of 0 and 30+.

### Screenshots
![image](https://user-images.githubusercontent.com/12830729/97786141-dca29e80-1ba9-11eb-8437-e80b27b1f21a.png)

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard7** [comment]
Hi @annedeg - we have gotten this question a few times already (and will advise the content team to add an FAQ). Re-adjusting the scales as per your suggestion is not something we're keen to do.

While adjusting the scales to go to 100 would make it easier to see extreme outliers, it would also mean that the regions that are currently a lot above the alert value would seem "less bad" in comparison. That is a misrepresentation of fact that we feel might lead users to draw the wrong conclusion from the data.

That said, we understand the underlying intention to see extreme outliers. That's a use case that we're still considering on how, when and if to best implement that.

**Comment by EwoutH** [comment]
@VWSCoronaDashboard7 I largely agree, especially with this part:

> it would also mean that the regions that are currently a lot above the alert value would seem "less bad" in comparison. 

Everything above 7 is too much, so >30 is already a high max value to display.

However, maybe an tick box could be added with something to "Adjust scale to extreme values". Then use a different color choropleth to display this map, to make it very clear the scale is adjusted.

A logarithmic scale could also be considered, since we're talking about exponential growth.
