### ISSUE TITLE
The label of the municipality map seems off when there is no data about its districts

### ISSUE THREAD

**Issue by dutchmartin** [minvws/nl-covid19-data-dashboard#910]
### Describe the bug, issue or concern
When you visit the page of a small municipality, the label of the municipality map does not have the label of what the map represents when there is no data about the districts of a municipality.

### To Reproduce
1. Go to [https://coronadashboard.government.nl/gemeente/GM0184/positief-geteste-mensen](https://coronadashboard.government.nl/gemeente/GM0184/positief-geteste-mensen)
2. Scroll down to 'Distribution of confirmed cases in municipality x' (in this example screenshot 1 & above stated url it is 'urk', but any small municipality will do)
3. We see the label 'Distribution of confirmed cases in Urk', but it shows the safety region of Flevoland.

### Expected behavior
Instead of the label showing 'Distribution of confirmed cases in **Urk**', it should state 'Distribution of confirmed cases in **Flevoland**'
But in a municipality like Amsterdam, where there is information about the various districts, the label obviously should still be displaying Amsterdam like in screenshot 2. 
### Screenshots
screenshot 1:
![image](https://user-images.githubusercontent.com/5509155/98860367-d2af5400-2463-11eb-8e99-39bbe6dc073a.png)
screenshot 2:
![image](https://user-images.githubusercontent.com/5509155/98862104-a8ab6100-2466-11eb-9334-bc4aaa6e4cba.png)

**Tested on desktop:**
 - OS: Debian
 - Browser: Firefox
 - Version 78.3.0ESR

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard7** [comment]
Interesting point. Both maps show the selected + all other municipalities within a safety region by the way. I think the confusion stems from the labeling. Something like "Distribution of confirmed cases in Urk and adjacent muncipalities in this safety region" would be better to describe this but is a lot of text to process. We'll think about a better label that's still concise.

**Comment by VWSCoronaDashboard7** [comment]
We've updated the labels to clarify this issue. This will go live by the next release at the latest so I'm considering this matter resolved.
