### ISSUE TITLE
Large blobs in page loads, 60+% overhead

### ISSUE THREAD

**Issue by MMeent** [minvws/nl-covid19-data-dashboard#956]
### Describe the bug, issue or concern

I noticed that a significant amount of data is stored in the `id=__NEXT_DATA__` script tag (some 515503 bytes, half a megabyte, out of 732471 total for `https://coronadashboard.government.nl`), and the data contained is mostly old (most recent timestamp = 2020-11-10T14:15:36Z).

It currently contains a significant, if not full, set of the daily infection data (accounting for >400kb of the 515kb), and I believe that it would be beneficial to either not include that data or include only the latest up-to-date values, and later request (and store locally) the historical data when required. This would save significantly on page load times, as the  `id=__NEXT_DATA__` script tag is positioned before the rest of the application javascript includes, blocking the page from going responsive. 

It also would save a lot on total traffic, as this data is injected in effectively every page and is therefore not usually cached by the browser.

### To Reproduce
check the size of the `__NEXT_DATA__` script tag 

### Expected behavior
Only the required data is included in the pages `__NEXT_DATA__` script tag

### Environment

**Desktop (please complete the following information):**
 - OS: Debian 10.9
 - Browser: FireFox
 - Version 83.0

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard10** [comment]
Thanks for bringing this up, we’ve had this issue on our list-of-things-to-improve for a while. It shouldn’t effect load time too much due to gzip but it’s worth looking into nonetheless. Will update this thread down the road.

**Comment by VWSCoronaDashboard** [comment]
@MMeent 

First of all, thanks for this! We really appreciate it when people think with us and indicate improvement points in the codebase.

Question for you.

How and where do you measure half a megabyte? I've made a PR (see above comment) to reduce the payload we sent in the homepage, but that's a reduction from ~70KB to ~40KB. Relatively speaking still a big chunk of savings, but nowhere close to the 500KB you are mentioning.

**Comment by VWSCoronaDashboard** [comment]
Solved for the homepage! 🚀
We'll slowly pick up other pages as well in time.
