### ISSUE TITLE
Slow loadtimes for resources, and regular 502s

### ISSUE THREAD

**Issue by MMeent** [minvws/nl-covid19-data-dashboard#958]
### Describe the bug, issue or concern

On my laptop, I see very slow load times of the assets of effectively all pages. Common load times are just over exactly 1m in time-to-first-byte for resources, and I otherwise also often see 502s in the console. Note that the secure connection is established, and after that 

This happens for both my browser and `curl` cli executions. Weirdly enough, my mobile phone (through wifi, same external IP) does not have this issue.

<details>
<summary>some references from 502-errors</summary>

```
 Reference #97.920a1602.1605638330.6acc184 
 Reference #97.a30a1602.1605638330.1969aaf5 
 Reference #97.a30a1602.1605638331.1969cad0 
```

</details>
<details>
<summary> output of `curl https://coronadashboard.government.nl --verbose > index.html`</summary>

```
* Rebuilt URL to: https://coronadashboard.government.nl/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 2.16.186.138...
* TCP_NODELAY set
* Connected to coronadashboard.government.nl (2.16.186.138) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [102 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [6953 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=NL; L='s-Gravenhage; O=Ministerie van Volksgezondheid, Welzijn en Sport; OU=Directie Communicatie; CN=coronadashboard.government.nl
*  start date: Aug 20 13:20:03 2020 GMT
*  expire date: Aug 20 13:20:03 2021 GMT
*  subjectAltName: host "coronadashboard.government.nl" matched cert's "coronadashboard.government.nl"
*  issuer: C=NL; O=KPN B.V.; CN=KPN PKIoverheid Server CA 2020
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x55e9ac7a1ea0)
} [5 bytes data]
> GET / HTTP/1.1
> Host: coronadashboard.government.nl
> User-Agent: curl/7.52.1
> Accept: */*
> 
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
} [5 bytes data]
  0     0    0     0    0     0      0      0 --:--:--  0:00:59 --:--:--     0< HTTP/2 200 
< content-type: text/html
< last-modified: Wed, 11 Nov 2020 15:54:21 GMT
< etag: W/"5fac092d-b1534"
< expires: Thu, 12 Nov 2020 11:35:04 GMT
< cache-control: max-age=300
< content-security-policy: default-src 'self' statistiek.rijksoverheid.nl; img-src 'self' statistiek.rijksoverheid.nl data:; style-src 'self' 'unsafe-inline'; script-src 'self' statistiek.rijksoverheid.nl;
< referrer-policy: origin
< x-content-type-options: nosniff
< x-frame-options: SAMEORIGIN
< x-xss-protection: 1; mode=block
< cache-control: no-cache, public
< date: Tue, 17 Nov 2020 19:30:58 GMT
< strict-transport-security: max-age=15768000 ; preload
< 
{ [2434 bytes data]
100  5284    0  5284    0     0     87      0 --:--:--  0:01:00 --:--:--  1082* Curl_http_done: called premature == 0
100  709k    0  709k    0     0  12035      0 --:--:--  0:01:00 --:--:--  175k
* Connection #0 to host coronadashboard.government.nl left intact
```

</details>

### To Reproduce
I've started noticing the issue about a week ago. 

### Expected behavior
Page loads as fast as when I use my phone.

### Screenshots
n/a

**Desktop (please complete the following information):**
 - OS: Debian 10.9
 - Browser: FireFox 83.0
 - Browser: curl 7.52.1

### Additional context
I've tried disabling HTTP2, but that didn't fix the slow load times.

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by VWSCoronaDashboard7** [comment]
Hi there! First off, thanks for the detailed write-up. It seems you're hitting the Akamai server correctly so it's odd that it would be slow for you. From the fact that your phone produces a snappy response, my deduction would be that it's not likely to be a networking issue either. 

Are there any local services you're running, such as your own DNS server or a VPN/firewall/antivirus service that could possibly interfere with your network traffic and cause this delay? If you're able to, I'd be keen to know if this issue is reproducible using a "live-cd" boot on your machine so we can rule out all these software configurations types of issues.

**Comment by MMeent** [comment]
I've since encountered this issue on my smartphone, whilst using the company wifi, indicating it's not (only) my PC.

Some environment parameters:
- We do not have a firewall (but do have NAT)
- We have a resolver which recieves DNS record timeouts of up to 20s, with regularly changing IPs.

This results in frequent new resolved ips for the akamai servers, so it is more likely that the new page resolves to a new server, which makes it more likely I hit an empty cache. Each time I encountered the issue (when watching the network tab) the reload was from another IP address than the previous.

- The problem occurs mostly for each first time a resource is loaded, subsequent requests don't have a 1m wait time. This is probably due to a cache miss, requiring that server to first cache the object.

- The issue _looks_ like the akamai-server fails to connect or times out whilst trying to refresh / gather its cache (as seen by the 1m timeout, that only happens once every set of same-resource-loads). 
I suspect you might have a L3 load balancer in front of the actual dashboard content-server, and if so, this issue could, or could not, be due to problems similar to https://www.niels-ole.com/cloud/aws/linux/2020/10/18/nlb-resets.html. That issue is effectively a problem related to using L3 load balancers instead of L4 load balancers, with multiple fronting load balancer IPs resolving to the same backing server.

- I usually got some resource request timeouts after refreshing the page a few times, but the frequency dropped sharply sometime today (though, just now (20:32 UTC+01:00) I once again had a 1-minute timeout)

<details>
<summary>some script I ran to test timeouts</summary>

This script generates files named `<ip>.timeout`. They contain `time` information about the request timings.

```
# The ips were extracted from some DNS lookups over the course of 2 hours. You can replace it with your own test set, if so desired.
akamai_ips=(2.16.186.185 2.16.110.90 2.16.110.24 184.86.103.209 184.86.103.198 23.3.88.43 23.3.88.64 92.123.250.66 92.123.250.112 95.101.82.178 95.101.82.115)
for ip in ${akamai_ips[@]}; do
  rm "${ip}.timeout";
  echo "testing ${ip}"
  for n in 1 2; do
    echo "attempt $n" >> "${ip}.timeout"
    /usr/bin/time -o "${ip}.timeout" --append -p curl --resolve "${ip}" "https://coronadashboard.government.nl" > /dev/null;
  done;
done;
```
Every once in a while the first attempt has a 1 minute delay before the data is received. Most of the time it is only for the first ip in the list (any order), but I've also seen it happen later in the iteration.
</details>

**Comment by VWSCoronaDashboard7** [comment]
Hi @MMeent thanks again for your elaborate research and reply. After exploring some options, we've re-applied the firewall config between edge and origin. We are now not seeing any 0 status codes (time-outs) anymore and assume the matter resolved. Feel free to (re)open if it's still bothering you!
